### ISSUE TITLE
Error: version mismatch: expected v6, found v5

### ISSUE THREAD

**Issue by mitra42** [ipfs/js-ipfs#1071]
- **Version**: ipfs v26
- **Platform**: OSX 
#### Description:

The latest version of JS-IPFS seems to be incompatible with the default swarm being recommended and generates the error version mismatch: expected v6, found v5 

#### Steps to reproduce the error:
Set package.json to have ipfs: "^0.26.0"  or "git+https://git@github.com/ipfs/js-ipfs.git"

#### Work around
Get the old version "git+https://git@github.com/ipfs/js-ipfs.git#319c1c9830262ab5c05bf99fc525d8883d3178cb",

It seems that JS's upgrade doesn't match the default swam - or at least the version of config Kyle gave us: 
IPFS options :{"repo":"/tmp/ipfs_dweb20171029","config":{"Addresses":{"Swarm":["/dns4/star-signal.cloud.ipfs.team/wss/p2p-webrtc-star"]}},"EXPERIMENTAL":{"pubsub":true}},

While I have a workaround I think this is critical, because any app that updates to the IPFS v0.26 (e.g. just by running npm update) is going to break their app.

**Comment by mitra42** [comment]
Note, I added this at first as a comment on https://github.com/ipfs/go-ipfs/issues/4250 which maybe a different cause, and anyway the problem/workaround occurs in JS

**Comment by richardschneider** [comment]
this may help https://github.com/ipfs/js-ipfs-repo/issues/152

**Comment by diasdavid** [comment]
This is correct for js-ipfs master, it should not be for js-ipfs 0.26 as deps are locked with semver. Are you sure you didn't install deps once and then switched the version? Check package-lock.json

The solution @richardschneider pointed out is correct, right now it is just a question of a version number that doens't mean anything for JS land for this specific version update.

Cleaning up the old repo and generating a new one should also fix it :)

**Comment by mitra42** [comment]
David - sorry, I don't understand your first paragraph. 
What I was doing, was switching the line in package.json, running npm update and then bundle. The changes were consistent, i.e. going between versions always had the effect expected (failure to start IFPS in anything except the version shown. 

I'm unclear what you mean about "cleaning up the old repo" - whose repo? Mine or IPFS's and what do you mean by "clean" it. 

I can confirm tnow that switching package.json to ipfs: "^0.26.0" works again.

**Comment by diasdavid** [comment]
I'm sorry, I should have been clearer. Let me explain again:

- js-ipfs 0.26.0 and all of its dependencies were released with semver locked on patch version updates (the ~), which protects it from any breaking changes that might happen on minor versions, something that would not happen if we used the ^. Installing js-ipfs from npm should always be fine or at least that is a promise I work really hard not to break and if that happens, it should be handled as a big fire 🔥 that needs to be put out quickly.
- In the way that npm works and due to js-ipfs giant dependency tree, I personally do not recommend to install modules individually unless you know exactly what npm is going to do. My recommendation is that everytime you want to experiment a new version, you update your package.json, you remove your package-lock.json and your node_modules forlder and then do a "clean" npm installs. Clean as it is a fresh install
- The IPFS Repo is where the config including the version number is stored. I believe you had a similar issue in the past when we changed the webrtc-star multiaddr to p2p-webrtc-star, where js-ipfs was failing unable to parse the old multiaddr, right? If you clean (delete) your repo, js-ipfs will create a new one and make sure that the latest is up to date. This should be a last resort solution.

Sorry for the hiccups. js-ipfs 0.27 should be out the door in less than 2 weeks, any particular feature you are looking for?

**Comment by mitra42** [comment]
Thanks for clarification, I wasnt aware of this procedure requirement to remove package-lock.json before doing an npm update, usually I do an "npm update" before a bundle, just to make sure I'm testing against latest versions.  

I"m not installing any IPFS modules individually only "ipfs: "^0.26.0. I *do* install Y modules individually, including Y-ipfs-connector. 

Are you suggesting that package.json should include "ipfs: "~0.26.0" in order to not update to 0.27.0, or that within ipfs you are using "~" on dependencies to avoid complex dependency caused breaks? 

Understood about cleaning repo, problem with that now is that anything I've "add'ed will get trashed since in most cases no-one will have that. 

For 0.27 - three issues in order of priority:

The most critical thing from my perspective is the bad ongoing bugs. 
https://github.com/ipfs/js-ipfs/issues/950 in particular is still a blocker for anything being released that uses JS IPFS since it crashes Firefox, and crashes the Chrome tab. 

And https://github.com/ipfs/js-ipfs/issues/1049 which means that there is no possible way to retrieve half the files that are uploaded (via the HTTP API) from Archive.org (files.cat or dag.get fails on short (unsharded) files.   That ones a big challenge because noone has even acknowledged we have a bug there despite its reproducability.

Third priority would be IPNS working in JS so we can implement naming things.

**Comment by kevingzhang** [comment]
I am running IPFS 0.27, new fresh install, get the same error:
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: version mismatch: expected v6, found v5
    at get (/Users/kevinzhang/github/DAO/code/barenode/node_modules/ipfs-repo/src/version.js:57:27)
    at store.get (/Users/kevinzhang/github/DAO/code/barenode/node_modules/ipfs-repo/src/version.js:31:9)
    at /Users/kevinzhang/github/DAO/code/barenode/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
[nodemon] app crashed - waiting for file changes before starting...


Any work around? or revert to install an older version?

**Comment by diasdavid** [comment]
@kevingzhang the simple workaround is to change the version number on your repo at ~/.jsipfs/version

**Comment by kevingzhang** [comment]
Thanks @diasdavid  I got the work around from #270 like this
const ipfsOptions = {
  repo: './path/to/another/dir',
  EXPERIMENTAL: {
    pubsub: true
  },
}
it works now

**Comment by olizilla** [comment]
@diasdavid I'm seeing this after updating js-ipfs from 0.26.0 to 0.27.3 with a pretty minimal config:

```
  node = new Ipfs({
    config: {
      Addresses: {
        Swarm: []
      }
    }
  })
```

in ipfs-companion https://github.com/ipfs/ipfs-companion/pull/320

I can remove my indexdb but i'll have to also get others who are reviewing this PR to do the same... should js-ipfs be auto-upgrading older repos?

**Comment by diasdavid** [comment]
@olizilla see https://github.com/ipfs/js-ipfs/issues/1115. tl;dr; we should have a utility to make devs life easier, until then it is up to the app developer. 

@pgte developed this solution - https://github.com/ipfs-shipyard/peerpad-core/blob/master/src/backend/migrate-ipfs-repo-if-necessary.js
