### ISSUE TITLE
jsipfs init failing in Windows

### ISSUE THREAD

**Issue by asyphus** [ipfs/js-ipfs#1119]
- **Version**:
js-ipfs version: 0.26.0
****
- **Platform**:
Windows 10 64-bit

- **Subsystem**:
interface-datastore

#### Description: When running "jsipfs init" I am getting an Invalid Key error.  I thought it might be because of the difference in backslashes and forward slashes where it is being initialized, but my attempts at resolving this failed.  Below is the output after running the init command:

initializing ipfs node at C:\Users\rober/.jsipfs
generating 2048-bit RSA keypair...done
peer identity: QmSwvZgqDU9eUGoNqkiLfStUrLKpf9k5nVL7EPGkGPVR2P
C:\Users\rober\AppData\Roaming\npm\node_modules\ipfs\node_modules\interface-datastore\src\key.js:46
      throw new Error(`Invalid key: ${this.toString()}`)
      ^

Error: Invalid key: /CIQFTFEEHEDF6KLBT32BFAGLXEZL4UWFNWM4LFTLMXQBCERZ6CMLX3Y
    at new Key (C:\Users\rober\AppData\Roaming\npm\node_modules\ipfs\node_modules\interface-datastore\src\key.js:46:13)
    at keyFromBuffer (C:\Users\rober\AppData\Roaming\npm\node_modules\ipfs\node_modules\ipfs-repo\src\blockstore.js:20:10)
    at cidToDsKey (C:\Users\rober\AppData\Roaming\npm\node_modules\ipfs\node_modules\ipfs-repo\src\blockstore.js:30:10)
    at Object.put (C:\Users\rober\AppData\Roaming\npm\node_modules\ipfs\node_modules\ipfs-repo\src\blockstore.js:80:17)
    at BlockService.put (C:\Users\rober\AppData\Roaming\npm\node_modules\ipfs\node_modules\ipfs-block-service\src\index.js:64:23)
    at waterfall (C:\Users\rober\AppData\Roaming\npm\node_modules\ipfs\node_modules\ipld-resolver\src\index.js:385:28)
    at nextTask (C:\Users\rober\AppData\Roaming\npm\node_modules\ipfs\node_modules\async\waterfall.js:16:14)
    at next (C:\Users\rober\AppData\Roaming\npm\node_modules\ipfs\node_modules\async\waterfall.js:23:9)
    at C:\Users\rober\AppData\Roaming\npm\node_modules\ipfs\node_modules\async\internal\onlyOnce.js:12:16
    at Object.serialize (C:\Users\rober\AppData\Roaming\npm\node_modules\ipfs\node_modules\ipld-dag-pb\src\util.js:27:3)

**Comment by diasdavid** [comment]
Hi @asyphus, Windows support only starts at v0.27 coming out soon https://github.com/ipfs/js-ipfs/issues/1095

**Comment by VictorBjelkholm** [comment]
Until 0.27 has been released, it's always useful if you could try the
latest code from the master branch on git. Some additional testing is
always welcome!

**Comment by asyphus** [comment]
Thanks! @VictorBjelkholm @diasdavid I'll try to get that running.

**Comment by diasdavid** [comment]
@asyphus you can now try out the just released v0.27.0! Released ann here https://github.com/ipfs/js-ipfs/issues/1095 \o/ Let us know if you encounter any issue
