### ISSUE TITLE
Enable Bitswap tests on Windows

### ISSUE THREAD

**Issue by vmx** [ipfs/js-ipfs#1313]
The [Bitswap test file](https://github.com/ipfs/js-ipfs/blob/64c3bfb45cda27e268655cc9a2bce28eebd09454/test/core/bitswap.spec.js#L26-L27) says that enabling the tests is blocked by https://github.com/ipfs/js-ipfsd-ctl/pull/205 which got merged. So it seems that the Bitswap tests could be enabled on Windows.

**Comment by dryajov** [comment]
Yes, it should be possible to enable it now.

**Comment by alanshaw** [comment]
Still not working unfortunately:

```
  1) bitswap "after each" hook:

     Uncaught Error: EBUSY: resource busy or locked, unlink 'C:\Windows\TEMP\ipfs-test-cb6c22963a56dc17c6cbeb51cb7936e2\datastore\LOG'

      at Object.fs.unlinkSync (fs.js:1081:18)

      at rimrafSync (node_modules\rimraf\rimraf.js:306:17)

      at node_modules\rimraf\rimraf.js:342:5

      at Array.forEach (<anonymous>)

      at rmkidsSync (node_modules\rimraf\rimraf.js:341:26)

      at rmdirSync (node_modules\rimraf\rimraf.js:334:7)

      at rimrafSync (node_modules\rimraf\rimraf.js:304:9)

      at node_modules\rimraf\rimraf.js:342:5

      at Array.forEach (<anonymous>)

      at rmkidsSync (node_modules\rimraf\rimraf.js:341:26)

      at rmdirSync (node_modules\rimraf\rimraf.js:334:7)

      at Function.rimrafSync [as sync] (node_modules\rimraf\rimraf.js:304:9)

      at Object.removeRepo (node_modules\ipfsd-ctl\src\utils\repo\nodejs.js:17:17)

      at Node.cleanup (node_modules\ipfsd-ctl\src\ipfsd-in-proc.js:181:15)

      at exec.stop (node_modules\ipfsd-ctl\src\ipfsd-in-proc.js:241:21)

      at done (src\core\components\stop.js:27:7)

      at node_modules\async\internal\parallel.js:39:9

      at node_modules\async\internal\once.js:12:16

      at replenish (node_modules\async\internal\eachOfLimit.js:61:25)

      at iterateeCallback (node_modules\async\internal\eachOfLimit.js:50:17)

      at node_modules\async\internal\onlyOnce.js:12:16

      at node_modules\async\internal\parallel.js:36:13

      at series (node_modules\ipfs-repo\src\index.js:257:17)

      at node_modules\async\internal\parallel.js:39:9

      at node_modules\async\internal\once.js:12:16

      at replenish (node_modules\async\internal\eachOfLimit.js:61:25)

      at iterateeCallback (node_modules\async\internal\eachOfLimit.js:50:17)

      at node_modules\async\internal\onlyOnce.js:12:16

      at node_modules\async\internal\parallel.js:36:13

      at node_modules\async\internal\parallel.js:39:9

      at node_modules\async\internal\once.js:12:16

      at replenish (node_modules\async\internal\eachOfLimit.js:61:25)

      at iterateeCallback (node_modules\async\internal\eachOfLimit.js:50:17)

      at node_modules\async\internal\onlyOnce.js:12:16

      at node_modules\async\internal\parallel.js:36:13

      at FSReqWrap.oncomplete (fs.js:149:15)
```

**Comment by diasdavid** [comment]
All good now, right?

**Comment by alanshaw** [comment]
trying it again here https://github.com/ipfs/js-ipfs/pull/1483
