### ISSUE TITLE
Node on different computer can't connect each other

### ISSUE THREAD

**Issue by minxinping0105** [ipfs/js-ipfs#1357]
System：ubuntu14.04
jsipfs Version： 0.28.2
Each Computer has run 'ipfs daemon', when connect to each other, ther errors is following"

```
root@dwrj167:~/Orbitdb/nodejs9.11.1/bin# ./jsipfs swarm connect /ip4/10.1.50.168/tcp/4002/ipfs/QmT3oRfkS4orcGT6kTzPzKgG7arM1KfugKgzVtg1vmtBGt
/root/Orbitdb/nodejs9.11.1/lib/node_modules/ipfs/src/cli/commands/swarm/connect.js:20
        throw err
        ^

Error: Error: dialed to the wrong peer, Ids do not match
    at parseError (/root/Orbitdb/nodejs9.11.1/lib/node_modules/ipfs/node_modules/ipfs-api/src/utils/send-request.js:16:17)
    at ClientRequest.<anonymous> (/root/Orbitdb/nodejs9.11.1/lib/node_modules/ipfs/node_modules/ipfs-api/src/utils/send-request.js:39:14)
    at Object.onceWrapper (events.js:272:13)
    at ClientRequest.emit (events.js:180:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:540:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at Socket.socketOnData (_http_client.js:445:20)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
```

**Comment by alanshaw** [comment]
I've tracked the error down to https://github.com/libp2p/js-libp2p-secio/blob/6d09b472ec8d96040c54fbee630dc0b117a628bb/src/handshake/crypto.js#L80

@dignifiedquire can you shed any light on this?

**Comment by alanshaw** [comment]
@minxinping0105 there's a new js-ipfs release out, would you mind checking if this error is still happening for you?

**Comment by diasdavid** [comment]
Hi @minxinping0105 3 releases happened since this was report, try out the new js-ipfs and let us know if it is still an issue.
