### ISSUE TITLE
Example: Exchange files in browser is broken - no `ipfs` module

### ISSUE THREAD

**Issue by PascalPrecht** [ipfs/js-ipfs#1424]
- **Version**: https://github.com/ipfs/js-ipfs/commit/c1ee2474b08928ad64dac9148b7852f6c272387e

#### Description:

Following the installation and run instructions of that tutorial results in the following error

```
❯ npm run bundle

> exchange-files-browser@0.0.0 bundle /Users/pascalprecht/projects/ipfs/js-ipfs/examples/exchange-files-in-browser
> browserify public/app.js > public/bundle.js

Error: Cannot find module 'ipfs' from '/Users/pascalprecht/projects/ipfs/js-ipfs/examples/exchange-files-in-browser/public'
    at /Users/pascalprecht/projects/ipfs/js-ipfs/examples/exchange-files-in-browser/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/Users/pascalprecht/projects/ipfs/js-ipfs/examples/exchange-files-in-browser/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/pascalprecht/projects/ipfs/js-ipfs/examples/exchange-files-in-browser/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/pascalprecht/projects/ipfs/js-ipfs/examples/exchange-files-in-browser/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/pascalprecht/projects/ipfs/js-ipfs/examples/exchange-files-in-browser/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/pascalprecht/projects/ipfs/js-ipfs/examples/exchange-files-in-browser/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:158:21)
```

Looking at the installed node_modules, the `ipfs` package is indeed missing.

#### Steps to reproduce the error:

```
$ npm install
$ npm run bundle
```

**Comment by fsdiogo** [comment]
That's weird, but it's happening to me too.

I tried changing the `package.json` dependency to `"ipfs": "0.29.3"`, deleted and reinstalled the `node_modules` and then everything worked as expected 🤔

I'll take a look at it. Thanks for reporting it!

**Comment by PascalPrecht** [comment]
@fsdiogo thanks for confirming!

I guess to get this quickly out of our way, we should PR the dependency version. Did find anything else?

**Comment by fsdiogo** [comment]
It seems to work by upgrading to `0.30.0`, so I've made a PR changing that! Thanks 👍
