### ISSUE TITLE
cannot find ipfs module  

### ISSUE THREAD

**Issue by yashwanth2804** [ipfs/js-ipfs#1442]
Error: Cannot find module 'ipfs' from 

```
Error: Cannot find module 'ipfs' from '/home/hasura/Videos/js-ipfs-master/examples/browser-browserify/src'
    at /home/hasura/Videos/js-ipfs-master/examples/browser-browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/hasura/Videos/js-ipfs-master/examples/browser-browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/hasura/Videos/js-ipfs-master/examples/browser-browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/hasura/Videos/js-ipfs-master/examples/browser-browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/hasura/Videos/js-ipfs-master/examples/browser-browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/hasura/Videos/js-ipfs-master/examples/browser-browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)

```

**Comment by alanshaw** [comment]
@yashwanth2804 run `npm install` in `/home/hasura/Videos/js-ipfs-master` and then again in `/home/hasura/Videos/js-ipfs-master/examples/browser-browserify`.

**Comment by alanshaw** [comment]
@yashwanth2804 did this solve your problem?

**Comment by yashwanth2804** [comment]
yes thanks
