### ISSUE TITLE
Already Piped

### ISSUE THREAD

**Issue by agahEbrahimi** [ipfs/js-ipfs#1446]
I have been attempting to work with ipfs-pubsub room but it randomly exits and gives this error. I have attempted the fixes in some issues on ipfs but they have not worked. Any ideas of how to fix it? 

My ipfs version is the latest stable version. 

These are the issues I am referring to: 
https://github.com/libp2p/js-libp2p-switch/issues/235
https://github.com/ipfs/js-ipfs/issues/1156

This is the error:
    throw new Error('already piped')
          ^

    Error: already piped
        at sink (/Users/behrad/Desktop/ColIDE/JS/node_modules/pull-pair/index.js:11:13)
        at consume (/Users/behrad/Desktop/ColIDE/JS/node_modules/pull-defer/sink.js:7:17)
        at consume (/Users/behrad/Desktop/ColIDE/JS/node_modules/pull-defer/sink.js:7:17)
        at Connection.consume (/Users/behrad/Desktop/ColIDE/JS/node_modules/pull-defer/sink.js:7:17)
        at pull (/Users/behrad/Desktop/ColIDE/JS/node_modules/pull-stream/pull.js:43:9)
        at Dialer.handle (/Users/behrad/Desktop/ColIDE/JS/node_modules/multistream-select/src/dialer/index.js:47:5)
        at attemptMuxerUpgrade (/Users/behrad/Desktop/ColIDE/JS/node_modules/ipfs/node_modules/libp2p-switch/src/dial.js:157:10)
        at gotWarmedUpConn (/Users/behrad/Desktop/ColIDE/JS/node_modules/ipfs/node_modules/libp2p-switch/src/dial.js:54:7)
        at Switch.dial (/Users/behrad/Desktop/ColIDE/JS/node_modules/ipfs/node_modules/libp2p-switch/src/dial.js:40:9)
        at _getPeerInfo (/Users/behrad/Desktop/ColIDE/JS/node_modules/ipfs/node_modules/libp2p/src/index.js:237:19)

**Comment by alanshaw** [comment]
@agahEbrahimi could you please upgrade to the latest js-ipfs? Your stack trace is referring to an old version of libp2p-switch.

@justuswilhelm a new version of libp2p-switch has been released if you do a fresh install of js-ipfs you should pick it up.

The new libp2p-switch has a [fix for handling an error in the protocol handshake](https://github.com/libp2p/js-libp2p-switch/commit/c18e0bd55a704825ce1feb64f294ebf954e44ca5) which _might_ fix your issue. Please shout if you're still seeing the issue (with updated stacktrace plz!) and we'll investigate further.

**Comment by agahEbrahimi** [comment]
Thank you @alanshaw 
That worked.

**Comment by caffeinum** [comment]
I have this issue too. We do use pubsub-room. I have the last versions of js-ipfs, libp2p and libp2p-switch(=0.40.7).

I wrote to this issue first: https://github.com/ipfs/js-ipfs/issues/1366#issuecomment-412256679

**Comment by jacobheun** [comment]
The latest hotfix for multistream-select, 0.14.3, should prevent the error from being thrown. It will now be caught and logged. I will continue testing this to see if the issue comes up. Once you have multistream-select@0.14.3 (new installs should get it), if you do hit this issue, please scream in my general direction with logs and I will take a look!

Just fyi, I have been testing this against pubsub-room, along with a few other sample projects and the error is being logged properly.

**Comment by th-ink** [comment]
thanks @jacobheun, I can confirm that I don't get the error with multistream-select@0.14.3

**Comment by mitra42** [comment]
How is multistream-select included, I'm not seeing (any version) in package-lock.json , and did a fresh install (from npm, not from github) yesterday.

**Comment by jacobheun** [comment]
It is used in libp2p (libp2p-switch and libp2p-circuit). `npm ls` should resolve it. I just did a fresh install from npm to verify.

```
└─┬ ipfs@0.31.4
  ├─┬ libp2p@0.23.1
  │ └─┬ libp2p-switch@0.40.7
  │   └── multistream-select@0.14.3  deduped
  └─┬ libp2p-circuit@0.2.1
    └── multistream-select@0.14.3
```

**Comment by mitra42** [comment]
Confirmed - looks  like I installed just before the release. I'll watch for the already piped errors (which I've been seeing regularly up till now)
