### ISSUE TITLE
libp2p new config

### ISSUE THREAD

**Issue by pgte** [ipfs/js-ipfs#1451]
I need a version of [the libp2p new config](https://github.com/libp2p/js-libp2p/pull/166) to land here so that I can fix https://github.com/ipfs-shipyard/peer-star-app/issues/1.
Any plans for this?

**Comment by alanshaw** [comment]
That was released in v0.22 of libp2p which js-ipfs currently depends on.

**Comment by pgte** [comment]
When passing classes instead of instances to the `modules.transport` and `modules.discovery`, I'm getting this error from what I believe is js-ipfs validation:

```
[1] "modules" must be an object
      at Object.exports.process (node_modules/joi/lib/errors.js:196:19)
      at internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:675:31)
      at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:138:23)
      at module.exports.internals.Any.root.attempt (node_modules/joi/lib/index.js:167:29)
      at Object.module.exports.validate (node_modules/ipfs/src/core/config.js:52:43)
      at new IPFS (node_modules/ipfs/src/core/index.js:36:22)
      at module.exports (src/transport/ipfs.js:9:16)
      at new App (src/app.js:16:17)
      at module.exports (src/app.js:9:10)
      at Context.it (test/app.spec.js:30:11)
```

**Comment by alanshaw** [comment]
Yes, it currently has to be an object like `{ transport: [], peerDiscovery: [] }`. This is the case in the libp2p module too.

Looking at the code, an object with a `peerInfo` property will be passed to `peerDiscovery` items if they are a function that can be new'd up.

https://github.com/libp2p/js-libp2p/blob/d9059dbad9b33e2c1434b5c13ff500ed34aa348f/src/index.js#L175

Transports don't get the `peerInfo`:

https://github.com/libp2p/js-libp2p/blob/master/src/index.js#L133

If that's not going to work for your use case then we'll need to open an issue in libp2p and come up with a better solution.

**Comment by pgte** [comment]
@alanshaw Ah right, I misunderstood the error. I remember now: indeed I was trying to get a peerInfo instance into the modules constructor, but it looks like I'm still not getting one.

I'm bringing this to libp2p [here](https://github.com/libp2p/js-libp2p/issues/222).

Thanks!
