### ISSUE TITLE
question: can I use DHT for generic LWW record store?

### ISSUE THREAD

**Issue by pgte** [ipfs/js-ipfs#1489]
I want to be able to save random key->value entries in the DHT.
I'm ok with not having any consistency guarantees (writes to the same key not being linearisable).
Is there any way I can use the current DHT implementation for this?

**Comment by pgte** [comment]
The main reason I'm asking this is that apparently I can save a record (at least `ipfs.dht.put(k, v)` returns), but when I do a `ipfs.dht.get(k)` with the same key, I get:

```js
Uncaught Error: Record key does not have a selector function
      at Object.bestRecord (node_modules/libp2p-record/src/selection.js:21:11)
      at waterfall (node_modules/libp2p-kad-dht/src/private.js:298:42)
      at nextTask (node_modules/async/waterfall.js:16:14)
      at next (node_modules/async/waterfall.js:23:9)
      at node_modules/async/internal/onlyOnce.js:12:16
      at waterfall (node_modules/libp2p-kad-dht/src/index.js:284:9)
      at node_modules/async/internal/once.js:12:16
      at next (node_modules/async/waterfall.js:21:29)
      at node_modules/async/internal/onlyOnce.js:12:16
      at waterfall (node_modules/libp2p-kad-dht/src/index.js:244:20)
      at nextTask (node_modules/async/waterfall.js:16:14)
      at next (node_modules/async/waterfall.js:23:9)
      at node_modules/async/internal/onlyOnce.js:12:16
      at setImmediate (node_modules/multihashing-async/src/utils.js:8:7)
      at Immediate.<anonymous> (node_modules/async/internal/setImmediate.js:27:16)
```

(where the key is a random string with no "/" characters)

**Comment by alanshaw** [comment]
If you still need an answer to this @pgte I think @vasco-santos is working on this so might be able to help.
