### ISSUE TITLE
pubsub err

### ISSUE THREAD

**Issue by mccoysc** [ipfs/js-ipfs#1546]
throw err
        ^

Error: Cannot read property 'subscribe' of undefined
    at parseError (C:\Users\mccoyzhou\AppData\Roaming\npm\node_modules\ipfs\node_modules\ipfs-api\src\utils\send-request.js:17:17)
    at ClientRequest.<anonymous> (C:\Users\mccoyzhou\AppData\Roaming\npm\node_modules\ipfs\node_modules\ipfs-api\src\utils\send-request.js:47:14)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)

**Comment by alanshaw** [comment]
Hi @mccoysc can you provide some more information? Do you have a code example you can paste here?

**Comment by tchardin** [comment]
I think this might be the same issue: 
(running with the default create-react-app setup and js-ipfs@0.32.0-rc.1)
```js
import React from 'react';
import IPFS from 'ipfs';

class ErrorCases extends React.Component {
  constructor() {
    super();
    this.node = new IPFS({
      repo: String(Math.random() + Date.now()),
      Experimental: {
        pubsub: true,
      },
      config: {
        Addresses: {
          Swarm: [
            '/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star',
          ],
        },
      },
    });
  }
  componentDidMount() {
    this.node.once('ready', () => {
      this.node.pubsub.subscribe('topic', console.log).catch(console.error);
    });
  }
  render() {
    return null;
  }
}
```
Error:
<img width="569" alt="screen shot 2018-09-11 at 9 58 03 pm" src="https://user-images.githubusercontent.com/19876116/45384316-f3728980-b60d-11e8-8660-000be5c9fd27.png">

**Comment by tchardin** [comment]
Fixed this btw. `Experimental` should be `EXPERIMENTAL`. Rookie mistake!

**Comment by alanshaw** [comment]
Yes, the [`pubsub` property doesn't get set on the libp2p node](https://github.com/libp2p/js-libp2p/blob/master/src/index.js#L96-L99) if you don't enable pubsub in the config.

@mccoysc this is likely the cause of your problem too.
