### ISSUE TITLE
error while initlizing

### ISSUE THREAD

**Issue by mccoysc** [ipfs/js-ipfs#1562]
jsipfs daemon --enable-dht-experiment --enable-pubsub-experiment
Initializing daemon...
Using wrtc for webrtc support

C:\Users\mccoyzhou\AppData\Roaming\npm\node_modules\ipfs\node_modules\libp2p\src\index.js:145
      if (t.filter(multiaddrs).length > 0) {
            ^

TypeError: t.filter is not a function
    at _modules.transport.forEach (C:\Users\mccoyzhou\AppData\Roaming\npm\node_modules\ipfs\node_modules\libp2p\src\index.js:145:13)
    at Array.forEach (<anonymous>)
    at Node.start (C:\Users\mccoyzhou\AppData\Roaming\npm\node_modules\ipfs\node_modules\libp2p\src\index.js:136:29)
    at gotConfig (C:\Users\mccoyzhou\AppData\Roaming\npm\node_modules\ipfs\src\core\components\libp2p.js:94:26)
    at store.get (C:\Users\mccoyzhou\AppData\Roaming\npm\node_modules\ipfs\node_modules\ipfs-repo\src\config.js:45:9)
    at C:\Users\mccoyzhou\AppData\Roaming\npm\node_modules\ipfs\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by alanshaw** [comment]
@mccoysc could you provide the code that is causing this error?

**Comment by mccoysc** [comment]
no code.
i just npm install ipfs -g and then type "jsipfs daemon --enable-dht-experiment --enable-pubsub-experiment" with enter and the error occours

**Comment by alanshaw** [comment]
I've just done a fresh install of ipfs@0.32 and I'm not getting the same error - could you try reinstalling?

**Comment by mccoysc** [comment]
i removed  the wrtc module

**Comment by alanshaw** [comment]
Closing as this can now be tracked upstream: https://github.com/libp2p/js-libp2p-webrtc-star/issues/156

**Comment by Juanperezc** [comment]
I have the same error runining the docker image
