### ISSUE TITLE
libp2p:floodsub:error Error: "/floodsub/1.0.0" not supported

### ISSUE THREAD

**Issue by kevinsimper** [ipfs/js-ipfs#1565]
Chrome Mac
Version 69.0.3497.81 (Official Build) (64-bit)

```
Invalid asm.js: Unexpected token
browser.js:133 jsipfs:preload:error Error: preload aborted for QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn    at t (https://cdn.jsdelivr.net/npm/ipfs@0.32.0/dist/index.js:129:235024)    at e (https://cdn.jsdelivr.net/npm/ipfs@0.32.0/dist/index.js:129:236033) +0ms
libp2p.js:98 Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmdvvnyCuJWMoP3Gw2Px5QtmKK3L2CBUmMGeQ6U7ksEkTY
browser.js:133 libp2p:floodsub:error Error: "/floodsub/1.0.0" not supported    at i.decodeFromReader (https://cdn.jsdelivr.net/npm/ipfs@0.32.0/dist/index.js:111:128524)    at https://cdn.jsdelivr.net/npm/ipfs@0.32.0/dist/index.js:121:659538    at f (https://cdn.jsdelivr.net/npm/ipfs@0.32.0/dist/index.js:121:660183)    at Object.e.read [as cb] (https://cdn.jsdelivr.net/npm/ipfs@0.32.0/dist/index.js:121:660270)    at l (https://cdn.jsdelivr.net/npm/ipfs@0.32.0/dist/index.js:111:74315)    at p (https://cdn.jsdelivr.net/npm/ipfs@0.32.0/dist/index.js:111:74566)    at Object.d.read (https://cdn.jsdelivr.net/npm/ipfs@0.32.0/dist/index.js:111:75096)    at f (https://cdn.jsdelivr.net/npm/ipfs@0.32.0/dist/index.js:121:660238)    at Object.e.read [as cb] (https://cdn.jsdelivr.net/npm/ipfs@0.32.0/dist/index.js:121:660070)    at l (https://cdn.jsdelivr.net/npm/ipfs@0.32.0/dist/index.js:111:74315) +0ms
```

```
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/ipfs@0.32.0/dist/index.js"></script>
    <script>
    const repo = "repo" + Math.random()
    const node = new Ipfs({
      repo,
      EXPERIMENTAL: {
        pubsub: true
      },
      config: {
        Addresses: {
          Swarm: [
            '/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star'
          ]
        }
      }
    })
    </script>
  </body>
</html>

```

**Comment by kevinsimper** [comment]
Found it, it is because of using localhost that this error appeared which hasn't been there before. If you use https it works as expected.

**Comment by alanshaw** [comment]
> it is because of using localhost that this error appeared

Would you mind elaborating please?

**Comment by kevinsimper** [comment]
@alanshaw Yes, sorry it was not clear.

I thought the reason was the page was hosted on `http://localhost:5000` because when it was deployed on `https://` the problem disappeared.

Now I tried to reproduce, the error does appear on `http://` anymore.

But I can find it on `file://xxx/index.html` but I know that `file://` will never be supported since the many differences.

![image](https://user-images.githubusercontent.com/1126497/45641929-7dba6200-bad4-11e8-94b2-4e41948fa89c.png)

**Comment by alanshaw** [comment]
I'm sorry but I still don't understand what the problem is here - what are you trying to do? The error message in your screenshot is different to the error in your first comment...

**Comment by whizzzkid** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments before 2023-06-05. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).
