### ISSUE TITLE
Make directory in MFS throws error

### ISSUE THREAD

**Issue by ajayrao80** [ipfs/js-ipfs#1580]
#### Description: I was working with MFS. 
Below code to create a directory throws error
Code:
```
ipfs.files.mkdir('/my/dir', (err) => {
  if (err) {
    console.error(err)
  }
})
```

Error:
```
NonFatalError: file does not exist
    at reduce (F:\classwork\madnet\node_modules\ipfs-mfs\src\core\utils\traverse-to.js:94:29)
    at F:\classwork\madnet\node_modules\async\reduce.js:70:9
    at replenish (F:\classwork\madnet\node_modules\async\internal\eachOfLimit.js:66:17)
    at F:\classwork\madnet\node_modules\async\internal\eachOfLimit.js:71:9
    at eachOfLimit (F:\classwork\madnet\node_modules\async\eachOfLimit.js:39:36)
    at F:\classwork\madnet\node_modules\async\internal\doLimit.js:9:16
    at reduce (F:\classwork\madnet\node_modules\async\reduce.js:69:32)
    at waterfall (F:\classwork\madnet\node_modules\ipfs-mfs\src\core\utils\traverse-to.js:77:11)
    at nextTask (F:\classwork\madnet\node_modules\async\waterfall.js:16:14)
    at next (F:\classwork\madnet\node_modules\async\waterfall.js:23:9)
```

**Comment by alanshaw** [comment]
If the parent directory doesn't exist you'll need to use the `parents` option to have it create `my` as well as `dir`.

https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#filesmkdir
