### ISSUE TITLE
Error when `ipfs.swarm.connect` or `jsipfs swarm connect`

### ISSUE THREAD

**Issue by nijynot** [ipfs/js-ipfs#1587]
First node
- **Version**: 0.32.2
- **Platform**: Windows 10
- **Subsystem**:

Second node
- **Version**: 0.32.2
- **Platform**: OS X
- **Subsystem**:

#### Description: I cannot connect two local nodes (127.0.0.1) with the `ipfs.swarm.connect` node.js API. Also tried to connect with the `jsipfs` CLI, but got same error, i.e. `jsipfs swarm connect` doesn't work either. Probably related to #1357.

Error when using `ipfs.swarm.connect`
```
Error: dialed to the wrong peer, Ids do not match
    at PeerId.createFromPubKey (C:\Users\...\node_modules\libp2p-secio\src\handshake\crypto.js:81:25)
    at pubKey.hash (C:\Users\...\node_modules\libp2p-secio\node_modules\peer-id\src\index.js:188:5)
    at Multihashing.Multihashing.digest (C:\Users\...\node_modules\libp2p-secio\node_modules\multihashing-async\src\index.js:33:5)
    at setImmediate (C:\Users\...\node_modules\libp2p-secio\node_modules\multihashing-async\src\utils.js:8:7)
    at Immediate.<anonymous> (C:\Users\...\node_modules\async\internal\setImmediate.js:27:16)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Error when using `jsipfs swarm connect`
```
Error: Error: dialed to the wrong peer, Ids do not match
    at parseError (C:\ProgramData\nvm\v8.9.4\node_modules\ipfs\node_modules\ipfs-api\src\utils\send-request.js:17:17)
    at ClientRequest.<anonymous> (C:\ProgramData\nvm\v8.9.4\node_modules\ipfs\node_modules\ipfs-api\src\utils\send-request.js:47:14)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
```

#### Steps to reproduce the error:

```
const addr = multiaddr('/ip4/127.0.0.1/tcp/4002/ipfs/...');
node.swarm.connect(addr, (err, res) => {
  console.log(err);
});
```
or
```
jsipfs daemon
jsipfs swarm connect /ip4/127.0.0.1/tcp/4002/ipfs/<id>
```

**Comment by kevinsimper** [comment]
I just tried connecting two nodes which are on localhost and it worked for me as you can see. Can you help me reproduce it? 😄 

```
$ jsipfs swarm connect /ip4/127.0.0.1/tcp/4001/ipfs/QmP6XPBTFo2PHM8TEyUdKaL35pjdAq8qqv8gtqp81eHncQ
connect /ip4/127.0.0.1/tcp/4001/ipfs/QmP6XPBTFo2PHM8TEyUdKaL35pjdAq8qqv8gtqp81eHncQ success
$ jsipfs --version
0.32.2
```

**Comment by alanshaw** [comment]
@nijynot 127.0.0.1 is the loopback address, so you'll not be able to connect to another node using that IP unless they're both running on the same machine and listening on different ports.

You've said above that you have a Windows and macOS machine my guess is that you're taking the loopback address of the first node and connecting to it from the second, but what that instructs the second node to do is connect to _itself_. It then notices that the peer ID of the node it has connected to and the peer ID in the multiaddr are not the same and so throws "Error: dialed to the wrong peer, Ids do not match".

You need to configure your two nodes to listen on IP addresses that are accessible from the other machine. On a local network this'll likely be a 192.168.x.x or 10.x.x.x IP.

Hope that helps.
