### ISSUE TITLE
ping error

### ISSUE THREAD

**Issue by xnetsc** [ipfs/js-ipfs#1616]
jsipfs ping QmW1apH3mUa1SGV9yPfnjhScVDWf3UmWsqCk87MdjbKNSj
Looking up peer QmW1apH3mUa1SGV9yPfnjhScVDWf3UmWsqCk87MdjbKNSj
Error
/usr/lib/node_modules/ipfs/node_modules/pull-stream/sinks/drain.js:22
                throw end
                ^

Error: Error
    at PingMessageStream._transform (/usr/lib/node_modules/ipfs/node_modules/ipfs-api/src/utils/ping-message-stream.js:18:15)
    at PingMessageStream.Transform._read (/usr/lib/node_modules/ipfs/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at PingMessageStream.Transform._write (/usr/lib/node_modules/ipfs/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/usr/lib/node_modules/ipfs/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/lib/node_modules/ipfs/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at PingMessageStream.Writable.write (/usr/lib/node_modules/ipfs/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/usr/lib/node_modules/ipfs/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:182:13)
    at addChunk (/usr/lib/node_modules/ipfs/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/usr/lib/node_modules/ipfs/node_modules/readable-stream/lib/_stream_readable.js:278:11)

**Comment by mccoysc** [comment]
and when ping in browser,error like this:

await ipfs.ping("QmZ6YuHZUJd6k9hbJNaNUZBsWfwZGv62piZMU6oxHPBtDx")
collect.js:7 Uncaught TypeError: Cannot read property 'push' of null
    at collect.js:7
    at reduce.js:8
    at drain.js:24
    at f (index.js:84)
    at Function.u [as push] (index.js:44)
    at e.ping (ping-pull-stream.js:79)
    at _getPeerInfo (index.js:339)
    at s (get-peer-info.js:54)
    at setImmediate.js:27
    at setImmediate.js:40
    at f (setImmediate.js:69)
    at r (setImmediate.js:109)

**Comment by achingbrain** [comment]
I've found the first error happens in the first few seconds of starting an IPFS node - after it's found a few peers the error stops occurring and the ping command starts working.

**Comment by mccoysc** [comment]
await ipfs.ping("QmXp22HFGvo29o6dsGnJwxaHvTieEqMGr1pS55ZsZUonMf")

TypeError: Cannot read property 'push' of null TypeError: Cannot read property 'push' of null

(anonymous)	@	collect.js:7
(anonymous)	@	reduce.js:8
(anonymous)	@	drain.js:24
f	@	index.js:84
c	@	index.js:69
s	@	index.js:29
i	@	drain.js:16
i	@	drain.js:12
e	@	pull.js:41
n	@	ping.js:8
(anonymous)	@	index.js:41
@alanshaw

**Comment by mccoysc** [comment]
and "QmXp22HFGvo29o6dsGnJwxaHvTieEqMGr1pS55ZsZUonMf" is my node itself.

**Comment by mccoysc** [comment]
and also, i ping others,"QmZ6YuHZUJd6k9hbJNaNUZBsWfwZGv62piZMU6oxHPBtDx",error again

**Comment by whizzzkid** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can follow the migration plan here https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).


This issue has been resolved in Helia! if this does not address your concern please let us know  by reopening this issue before 2023-06-05!
