### ISSUE TITLE
Fails to init with Node.js 11.x - Lock FcntlFlock failed: EINVAL, Invalid argument

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#1700]
nodejs11.js

```js
const IPFS = require('ipfs')
const node = new IPFS({ repo: '/tmp/ipfs-' + Date.now() })
node.on('ready', () => console.log('ready'))
```

Output:

```console
$ node --version
v11.1.0
$ node nodejs11.js 
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Lock FcntlFlock of /tmp/ipfs-1541587567155/repo.lock failed: EINVAL, Invalid argument
    at fs.close (/Users/alan/Desktop/test/node_modules/lock-me/src/unix.js:20:14)
    at /Users/alan/Desktop/test/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:148:20)
Emitted 'error' event at:
    at done (/Users/alan/Desktop/test/node_modules/ipfs/src/core/components/init.js:22:14)
    at /Users/alan/Desktop/test/node_modules/async/internal/once.js:12:16
    at next (/Users/alan/Desktop/test/node_modules/async/waterfall.js:21:29)
    at /Users/alan/Desktop/test/node_modules/async/internal/onlyOnce.js:12:16
    at waterfall (/Users/alan/Desktop/test/node_modules/ipfs-repo/src/index.js:138:9)
    at /Users/alan/Desktop/test/node_modules/async/internal/once.js:12:16
    at next (/Users/alan/Desktop/test/node_modules/async/waterfall.js:21:29)
    at /Users/alan/Desktop/test/node_modules/async/internal/onlyOnce.js:12:16
    at _locker.lock (/Users/alan/Desktop/test/node_modules/ipfs-repo/src/index.js:170:16)
    at lockFn (/Users/alan/Desktop/test/node_modules/lock-me/src/index.js:55:16)
```

https://github.com/dignifiedquire/lock-me/issues/4

**Comment by dignifiedquire** [comment]
There were some fixes done recently in https://github.com/baudehlo/node-fs-ext 
Can you check with and without it installed (it is an optional dependency) and also if does pull in the latest version?

**Comment by hugomrdias** [comment]
For the record this code doesn't work anymore https://github.com/baudehlo/node-fs-ext/blob/master/fs-ext.js#L139-L146

I have a PR pending to fix this in ipfs-repo.
