### ISSUE TITLE
Error docker image webrtc support

### ISSUE THREAD

**Issue by Juanperezc** [ipfs/js-ipfs#1708]
I have the next error when I run the docker image
`docker run -it -p 4002:4002 -p 4003:4003 -p 5002:5002 -p 9090:9090 ipfs/js-ipfs:latest`
```
Using /root/.jsipfs as IPFS repository
initializing ipfs node at /root/.jsipfs
generating 2048-bit RSA keypair...done
peer identity: QmWLfEowFGrRV4KzaJCVSDg8LeE1CxPzkZmXMR98yqerd6
to get started, enter:

        jsipfs cat /ipfs/QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr/readme

Initializing IPFS daemon...
Using wrtc for webrtc support
/usr/src/app/node_modules/libp2p/src/index.js:145
      if (t.filter(multiaddrs).length > 0) {
            ^

TypeError: t.filter is not a function
    at _modules.transport.forEach (/usr/src/app/node_modules/libp2p/src/index.js:145:13)
    at Array.forEach (<anonymous>)
    at Node.start (/usr/src/app/node_modules/libp2p/src/index.js:136:29)
    at gotConfig (/usr/src/app/src/core/components/libp2p.js:95:26)
    at store.get (/usr/src/app/node_modules/ipfs-repo/src/config.js:45:9)
    at fs.readFile (/usr/src/app/node_modules/datastore-fs/src/index.js:218:7)
    at /usr/src/app/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
```

**Comment by alanshaw** [comment]
@Juanperezc this should have been fixed by #1663. I'm going to assume all is well but if you can test with current master and let me know if not we can investigate further.
