### ISSUE TITLE
RangeError: Source is too large

### ISSUE THREAD

**Issue by tyvdh** [ipfs/js-ipfs#1751]
Trying to `ipfs.pin.add` a fairly large dag cid. According to https://www.npmjs.com/package/object-sizeof it's 230,000 bytes. Still pretty far from the 1MB limit though. Are there other constraints I'm missing?

`"ipfs": "^0.31.7",`
`$ node --version -> v10.9.0`

```
RangeError: Source is too large
    at Uint8Array.set (<anonymous>)
    at Decoder._decode (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/borc/src/decoder.js:552:17)
    at Decoder.decodeFirst (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/borc/src/decoder.js:576:10)
    at Object.exports.deserialize (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/ipld-dag-cbor/src/util.js:103:28)
    at waterfall (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/ipld/src/index.js:376:18)
    at nextTask (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/waterfall.js:16:14)
    at next (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/waterfall.js:23:9)
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/onlyOnce.js:12:16
    at getMany (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/ipfs-bitswap/src/index.js:207:9)
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/map.js:32:9
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/once.js:12:16
    at iteratorCallback (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/eachOf.js:60:13)
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/onlyOnce.js:12:16
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/map.js:29:13
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/once.js:12:16
    at next (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/waterfall.js:21:29)
From previous event:
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/build/ipfs/syncGlyphs.js:77:8
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/mongoose/lib/model.js:4495:16
    at process.nextTick (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/mongoose/lib/helpers/query/completeMany.js:35:39)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by alanshaw** [comment]
@tyvdh are you able to re-check with js-ipfs 0.34?

**Comment by tyvdh** [comment]
Sorry, I've long since given up on ipfs.
