### ISSUE TITLE
Error: Invalid version, must be a number equal to 1 or 0

### ISSUE THREAD

**Issue by tyvdh** [ipfs/js-ipfs#1752]
Running a number of `ipfs.dag.put` requests flawlessly and then running `ipfs.pin.add` on each of their cids. However when I go to `ipfs.pin.ls` I get a long list of these errors.

```
Error: Invalid version, must be a number equal to 1 or 0
    at Function.validateCID (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/cids/src/index.js:235:13)
    at new CID (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/cids/src/index.js:105:9)
    at toB58String (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/ipfs/src/core/components/pin.js:26:10)
    at nodes.map (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/ipfs/src/core/components/pin.js:60:35)
    at Array.map (<anonymous>)
    at dag._getRecursive (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/ipfs/src/core/components/pin.js:60:12)
    at mapAsync (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/ipfs/src/core/components/dag.js:160:11)
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/map.js:32:9
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/once.js:12:16
    at eachOfArrayLike (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/eachOf.js:53:9)
    at exports.default (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/eachOf.js:9:5)
    at _asyncMap (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/map.js:25:5)
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/doParallel.js:20:16
    at self.dag.get (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/ipfs/src/core/components/dag.js:155:9)
    at _get (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/ipld/src/index.js:143:9)
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/once.js:12:16
```

Any ideas?

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
