### ISSUE TITLE
The libp2p node is not started yet

### ISSUE THREAD

**Issue by Elexy** [ipfs/js-ipfs#1761]
Version: commit 593334bc
Platform: Linux js-ipfs-benchmarking 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Subsystem: ibp2p

running any of the tests from https://github.com/ipfs/benchmarks results in the error below, whereas earlier this week the tests ran without this error.

```
Dec 07 20:13:05 ip-172-31-44-15 node[6955]: AssertionError [ERR_ASSERTION]: The libp2p node is not started yet
Dec 07 20:13:05 ip-172-31-44-15 node[6955]:     at Node.dialProtocol (/home/ubuntu/ipfs/tests/node_modules/libp2p/src/index.js:303:5)
Dec 07 20:13:05 ip-172-31-44-15 node[6955]:     at libp2p.dialProtocol (/home/ubuntu/ipfs/tests/node_modules/ipfs-bitswap/src/network.js:169:21)
Dec 07 20:13:05 ip-172-31-44-15 node[6955]:     at Dialer._switch.dial [as callback] (/home/ubuntu/ipfs/tests/node_modules/libp2p/src/index.js:314:27)
Dec 07 20:13:05 ip-172-31-44-15 node[6955]:     at waterfall (/home/ubuntu/ipfs/tests/node_modules/libp2p-switch/src/dial.js:110:12)
Dec 07 20:13:05 ip-172-31-44-15 node[6955]:     at /home/ubuntu/ipfs/tests/node_modules/async/internal/once.js:12:16
Dec 07 20:13:05 ip-172-31-44-15 node[6955]:     at next (/home/ubuntu/ipfs/tests/node_modules/async/waterfall.js:21:29)
Dec 07 20:13:05 ip-172-31-44-15 node[6955]:     at /home/ubuntu/ipfs/tests/node_modules/async/internal/onlyOnce.js:12:16
Dec 07 20:13:05 ip-172-31-44-15 node[6955]:     at waterfall (/home/ubuntu/ipfs/tests/node_modules/libp2p-switch/src/dial.js:160:7)
Dec 07 20:13:05 ip-172-31-44-15 node[6955]:     at /home/ubuntu/ipfs/tests/node_modules/async/internal/once.js:12:16
Dec 07 20:13:05 ip-172-31-44-15 node[6955]:     at next (/home/ubuntu/ipfs/tests/node_modules/async/waterfall.js:21:29)
```
#### Type: bug
Critical - System crash, application panic.

**Comment by daviddias** [comment]
@Elexy mind doing a `npm ls libp2p` so that we know which libp2p version is being used? //cc @vasco-santos @jacobheun

**Comment by jacobheun** [comment]
I pulled down benchmark and wasn't able to reproduce the issue. I ran the `local-node` tests. I did have to change `peer.files.add` to `peer.add` due to the latest js-ipfs API changes. I ran the tests against `js-ipfs#master` and `js-ipfs#593334b`.

**Comment by jacobheun** [comment]
@alanshaw if you could point me to a CI build with it when you have one I can take a look at that; seeing what's going on around the failure would be helpful. We should probably look at changing that behavior in libp2p regardless. More immediately we could just return an error if the node isn't started, rather than throwing an assertion. 

Longer term, it might be worth looking at having a queue for dials that are attempted offline that can then be initiated once startup has been completed.

**Comment by alanshaw** [comment]
https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs/detail/PR-856/80/pipeline/262

**Comment by jacobheun** [comment]
Okay, that looks like there are some dials trying to happen from bitswap after libp2p is or has shut down.  I'll look into switching the assert over to a returned error instead and make sure we don't hit any side effects from that change.
