### ISSUE TITLE
Callback was already called when jsipfs init

### ISSUE THREAD

**Issue by xxyao123** [ipfs/js-ipfs#1794]
Version: 0.34.0
Platform: termux(linux aarch64 Android)
Subsystem: Node: 8.14.0
Type: Bug
Severity: Medium
Description:
Attempting to create an IPFS node using "jsipfs init" throws "Callback was already called." error.

jsipfs init
initializing ipfs node at /data/data/com.termux/files/home/.jsipfs
generating 2048-bit RSA keypair...done
peer identity: QmQGiDbUKsu2J8V3Dhjt48zs5AtJbbGJunveD1Cgd1qzqq
(node:14926) UnhandledPromiseRejectionWarning: Error: Callback was already called.
    at /data/data/com.termux/files/usr/lib/node_modules/ipfs/node_modules/async/internal/onlyOnce.js:9:32
    at _locker.lock (/data/data/com.termux/files/usr/lib/node_modules/ipfs/node_modules/ipfs-repo/src/index.js:170:16)
    at lock.then.catch.err (/data/data/com.termux/files/usr/lib/node_modules/ipfs/node_modules/ipfs-repo/src/lock.js:40:19)

**Comment by alanshaw** [comment]
@xxyao123 can you verify you have the same issue when using node.js 10?

**Comment by xxyao123** [comment]
I tried to use nodejs 10.14,  still got same result

**Comment by alanshaw** [comment]
@xxyao123 any chance you can try this once more on Node.js 10 with the official 0.34 release? 🙏

**Comment by alanshaw** [comment]
ping @xxyao123

**Comment by alanshaw** [comment]
closing due to inactivity
