### ISSUE TITLE
options.progress is not a function error

### ISSUE THREAD

**Issue by vmx** [ipfs/js-ipfs#1810]
- **Version**: HEAD
- **Platform**: Linux

#### Severity:

Critical

#### Description:

Tests are failing due to:

```
Debug: internal, implementation, error 
    AssertionError: expected [Error: options.progress is not a function] to not exist
    at Duplex.ipfs.files.write (/home/vmx/tmp/js-ipfs/node_modules/interface-ipfs-core/js/src/files-mfs/write.js:47:28)
    at Duplex.f (/home/vmx/tmp/js-ipfs/node_modules/once/once.js:25:25)
    at Object.onceWrapper (events.js:273:13)
    at Duplex.emit (events.js:182:13)
    at Duplex.EventEmitter.emit (domain.js:441:20)
    at send (/home/vmx/tmp/js-ipfs/node_modules/ipfs-http-client/src/utils/send-files-stream.js:101:26)
    at f (/home/vmx/tmp/js-ipfs/node_modules/once/once.js:25:25)
    at streamToJsonValue (/home/vmx/tmp/js-ipfs/node_modules/ipfs-http-client/src/utils/send-request.js:29:5)
    at streamToValue (/home/vmx/tmp/js-ipfs/node_modules/ipfs-http-client/src/utils/stream-to-json-value.js:30:5)
    at concat (/home/vmx/tmp/js-ipfs/node_modules/ipfs-http-client/src/utils/stream-to-value.js:12:22)
    at ConcatStream.<anonymous> (/home/vmx/tmp/js-ipfs/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:187:15)
    at ConcatStream.EventEmitter.emit (domain.js:459:23)
    at finishMaybe (/home/vmx/tmp/js-ipfs/node_modules/readable-stream/lib/_stream_writable.js:643:14)
    at afterWrite (/home/vmx/tmp/js-ipfs/node_modules/readable-stream/lib/_stream_writable.js:493:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

#### Steps to reproduce the error:

npm run test

**Comment by vmx** [comment]
This issue should go away once https://github.com/ipfs/js-ipfs-unixfs-importer/pull/14 is merged and released.
