### ISSUE TITLE
`run-in-electron` example not working

### ISSUE THREAD

**Issue by guoliu** [ipfs/js-ipfs#2011]
- **Version**:
js-ipfs version: 0.35.0-
Repo version: 7
System version: x64/darwin
Node.js version: v11.10.1

- **Platform**:
macOS 10.14.3

#### Description: 
`run-in-electron` example throws error:

```
App threw an error during load
/Users/liuguo/repos/js-ipfs/examples/run-in-electron/node_modules/pull-stream-to-async-iterator/index.js:4
  return (async function * () {
                         ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:606:28)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/liuguo/repos/js-ipfs/examples/run-in-electron/node_modules/async-iterator-to-pull-stream/index.js:2:20)
```

Looks like due to `async-iterator-to-pull-stream` not exporting transpiled ES5 code. See: https://github.com/alanshaw/pull-stream-to-async-iterator/issues/1

How is this example intended to work originally, am I missing something?

#### Steps to reproduce the error:

Run `npm start` in `examples/run-in-electron`

**Comment by hugomrdias** [comment]
FYI im in the process of adding support for electron-main and electron-renderer to aegir

**Comment by guoliu** [comment]
@hugomrdias thanks for the fast response!
