### ISSUE TITLE
IPFS Fails to start with nodejs_gc_runs_total has already been registered

### ISSUE THREAD

**Issue by KeithSSmith** [ipfs/js-ipfs#2019]
- **Version**: 0.35.0
- **Platform**: Docker image node:10-jessie
- **Subsystem**: Node.js10.15.3

#### Type:
Bug

#### Severity:
Medium

#### Description:
Building an updated Dockerfile (https://github.com/KeithSSmith/js-ipfs-docker/blob/master/Dockerfile) and the steps above allow the Docker image to build and initialize but when the Daemon is started it fails to start with the error:

```
ipfs:cli Error: A metric with the name nodejs_gc_runs_total has already been registered.
```

#### Steps to reproduce the error:
Build Docker image from Dockerfile referenced above and execute/run a container based on the image build. I have collected the DEBUG log and it is as follows:

```
# DEBUG=* jsipfs daemon
Initializing IPFS daemon...
js-ipfs version: 0.35.0
System version: x64/linux
Node.js version: 10.15.3
  ipfs:daemon starting +0ms
  ipfs:daemon failed to load optional electron-webrtc dependency +1ms
  ipfs:daemon failed to load optional webrtc dependency +3ms
  ipfs booting +0ms
  repo opening at: /root/.jsipfs +0ms
  repo init check +5ms
  repo:version comparing version: 7 and 7 +0ms
  repo init null { config: true, spec: true, version: undefined } +11ms
  repo:lock locking /root/.jsipfs/repo.lock +0ms
  repo aquired repo.lock +16ms
  repo creating datastore +1ms
  repo creating blocks +7ms
  repo creating keystore +8ms
  repo all opened +0ms
  ipfs:state -> initializing +0ms
  ipfs init +49ms
  ipfs pre-start +0ms
  ipfs no keychain, use --pass +2ms
  ipfs peer created +28ms
  ipfs Loaded pins from the datastore +26ms
  ipfs:state -> stopped +56ms
  ipfs starting +1ms
  ipfs:state -> starting +1ms
  libp2p:switch:dialer create: 8 peer limit, 10000 dial timeout +0ms
  libp2p:connection-manager options: {"maxPeers":500,"minPeers":200,"maxData":null,"maxSentData":null,"maxReceivedData":null,"maxEventLoopDelay":null,"pollInterval":2000,"movingAverageInterval":60000,"defaultPeerValue":1,"maxPeersPerProtocol":{}} +0ms
  libp2p:switch:transport adding Circuit +0ms
  libp2p libp2p is starting +0ms
  libp2p:switch:transport adding TCP +8ms
  libp2p:switch:transport adding WebSockets +2ms
  libp2p:switch:transport adding undefined +1ms
  latency-monitor:LatencyMonitor latencyCheckIntervalMs: 500 dataEmitIntervalMs: 2000 +0ms
  latency-monitor:LatencyMonitor Expecting ~0.25 events per summary +1ms
  latency-monitor:LatencyMonitor Using process.hrtime for timing +0ms
  latency-monitor:LatencyMonitor localData: { deltaOffset: 459, startTime: [ 8476025, 76175921 ] } +0ms
  libp2p:switch The switch is starting +0ms
  libp2p:tcp:listen Listening on 4002 0.0.0.0 +0ms
  libp2p:websocket-star:multi listen on 0 server(s) with id QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv +0ms
  libp2p:switch The switch has started +27ms
  libp2p:mdns query ipfs.local +0ms
  libp2p libp2p has started +73ms
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv
Swarm listening on /ip4/172.17.0.4/tcp/4002/ipfs/QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv
Swarm listening on /ip4/172.17.0.4/tcp/4003/ws/ipfs/QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv
Swarm listening on /p2p-circuit/ipfs/QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv
Swarm listening on /p2p-circuit/ip4/127.0.0.1/tcp/4002/ipfs/QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv
Swarm listening on /p2p-circuit/ip4/172.17.0.4/tcp/4002/ipfs/QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv
Swarm listening on /p2p-circuit/ip4/127.0.0.1/tcp/4003/ws/ipfs/QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv
Swarm listening on /p2p-circuit/ip4/172.17.0.4/tcp/4003/ws/ipfs/QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv
  ipfs:mfs:lock Queuing read operation +0ms
  ipfs:mfs:lock Starting read operation +1ms
  ipfs:mfs:stat Fetching stats for / +0ms
  libp2p connecting to discovered peer +8ms
  libp2p:switch:dial starting dial queue to QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z +0ms
  libp2p:connection-manager QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv: connected to QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z +88ms
  libp2p:connection-manager checking limit of maxPeers. current value: 1 of 500 +0ms
  libp2p:connection-manager checking protocol limit. current value of ip4 is 1 +1ms
  libp2p:connection-manager checking protocol limit. current value of tcp is 1 +0ms
  libp2p:connection-manager checking protocol limit. current value of ipfs is 1 +0ms
  libp2p:connection-manager checking protocol limit. current value of ip6 is 1 +0ms
  libp2p:conn:out:QmSF16jD dialing QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z +0ms
  libp2p:conn:out:QmSF16jD dialing transport TCP +2ms
  libp2p:switch:transport dialing TCP [ '/ip4/104.236.176.52/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z',
  '/ip6/2604:a880:1:20::1f9:9001/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z' ] +81ms
  libp2p:switch:dialer dialMany:start +97ms
  libp2p:switch:dialer dialSingle: QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z:/ip4/104.236.176.52/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z +1ms
  libp2p connecting to discovered peer +11ms
  libp2p:switch:dial starting dial queue to QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ +11ms
  libp2p:connection-manager QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv: connected to QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ +8ms
  libp2p:connection-manager checking limit of maxPeers. current value: 2 of 500 +0ms
  libp2p:connection-manager checking protocol limit. current value of ip4 is 2 +1ms
  libp2p:connection-manager checking protocol limit. current value of tcp is 2 +0ms
  libp2p:connection-manager checking protocol limit. current value of ipfs is 2 +0ms
  libp2p:conn:out:QmSF16jD dialing QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ +0ms
  libp2p:conn:out:QmSF16jD dialing transport TCP +1ms
  libp2p:switch:transport dialing TCP [ '/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ' ] +6ms
  libp2p:switch:dialer dialMany:start +5ms
  libp2p:switch:dialer dialSingle: QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ:/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ +0ms
  libp2p connecting to discovered peer +5ms
  libp2p:switch:dial starting dial queue to QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM +5ms
  libp2p:connection-manager QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv: connected to QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM +4ms
  libp2p:connection-manager checking limit of maxPeers. current value: 3 of 500 +0ms
  libp2p:connection-manager checking protocol limit. current value of ip4 is 3 +0ms
  libp2p:connection-manager checking protocol limit. current value of tcp is 3 +1ms
  libp2p:connection-manager checking protocol limit. current value of ipfs is 3 +0ms
  libp2p:connection-manager checking protocol limit. current value of ip6 is 2 +0ms
  libp2p:conn:out:QmSF16jD dialing QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM +0ms
  libp2p:conn:out:QmSF16jD dialing transport TCP +1ms
  libp2p:switch:transport dialing TCP [ '/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM',
  '/ip6/2604:a880:1:20::203:d001/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM' ] +7ms
  libp2p:switch:dialer dialMany:start +7ms
  libp2p:switch:dialer dialSingle: QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM:/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM +0ms
  libp2p connecting to discovered peer +7ms
  libp2p:switch:dial starting dial queue to QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm +7ms
  libp2p:connection-manager QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv: connected to QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm +6ms
  libp2p:connection-manager checking limit of maxPeers. current value: 4 of 500 +0ms
  libp2p:connection-manager checking protocol limit. current value of ip4 is 4 +0ms
  libp2p:connection-manager checking protocol limit. current value of tcp is 4 +0ms
  libp2p:connection-manager checking protocol limit. current value of ipfs is 4 +0ms
  libp2p:connection-manager checking protocol limit. current value of ip6 is 3 +0ms
  libp2p:conn:out:QmSF16jD dialing QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm +0ms
  libp2p:conn:out:QmSF16jD dialing transport TCP +2ms
  libp2p:switch:transport dialing TCP [ '/ip4/162.243.248.213/tcp/4001/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm',
  '/ip6/2604:a880:0:1010::23:d001/tcp/4001/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm' ] +7ms
  libp2p:switch:dialer dialMany:start +7ms
  libp2p:switch:dialer dialSingle: QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm:/ip4/162.243.248.213/tcp/4001/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm +0ms
  libp2p connecting to discovered peer +8ms
  libp2p:switch:dial starting dial queue to QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu +8ms
  libp2p:connection-manager QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv: connected to QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu +7ms
  libp2p:connection-manager checking limit of maxPeers. current value: 5 of 500 +0ms
  libp2p:connection-manager checking protocol limit. current value of ip4 is 5 +1ms
  libp2p:connection-manager checking protocol limit. current value of tcp is 5 +0ms
  libp2p:connection-manager checking protocol limit. current value of ipfs is 5 +0ms
  libp2p:connection-manager checking protocol limit. current value of ip6 is 4 +0ms
  libp2p:conn:out:QmSF16jD dialing QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu +0ms
  libp2p:conn:out:QmSF16jD dialing transport TCP +2ms
  libp2p:switch:transport dialing TCP [ '/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu',
  '/ip6/2400:6180:0:d0::151:6001/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu' ] +7ms
  libp2p:switch:dialer dialMany:start +7ms
  libp2p:switch:dialer dialSingle: QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu:/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu +0ms
  libp2p connecting to discovered peer +6ms
  libp2p:switch:dial starting dial queue to QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64 +6ms
  libp2p:connection-manager QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv: connected to QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64 +6ms
  libp2p:connection-manager checking limit of maxPeers. current value: 6 of 500 +0ms
  libp2p:connection-manager checking protocol limit. current value of ip4 is 6 +0ms
  libp2p:connection-manager checking protocol limit. current value of tcp is 6 +0ms
  libp2p:connection-manager checking protocol limit. current value of ipfs is 6 +0ms
  libp2p:connection-manager checking protocol limit. current value of ip6 is 5 +0ms
  libp2p:conn:out:QmSF16jD dialing QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64 +0ms
  libp2p:conn:out:QmSF16jD dialing transport TCP +2ms
  libp2p:switch:transport dialing TCP [ '/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64',
  '/ip6/2604:a880:800:10::4a:5001/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64' ] +6ms
  libp2p:switch:dialer dialMany:start +6ms
  libp2p:switch:dialer dialSingle: QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64:/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64 +0ms
  libp2p connecting to discovered peer +6ms
  libp2p:switch:dial starting dial queue to QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd +6ms
  libp2p:connection-manager QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv: connected to QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd +6ms
  libp2p:connection-manager checking limit of maxPeers. current value: 7 of 500 +0ms
  libp2p:connection-manager checking protocol limit. current value of ip4 is 7 +0ms
  libp2p:connection-manager checking protocol limit. current value of tcp is 7 +0ms
  libp2p:connection-manager checking protocol limit. current value of ipfs is 7 +0ms
  libp2p:connection-manager checking protocol limit. current value of ip6 is 6 +0ms
  libp2p:conn:out:QmSF16jD dialing QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd +0ms
  libp2p:conn:out:QmSF16jD dialing transport TCP +2ms
  libp2p:switch:transport dialing TCP [ '/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd',
  '/ip6/2a03:b0c0:0:1010::23:1001/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd' ] +6ms
  libp2p:switch:dialer dialMany:start +7ms
  libp2p:switch:dialer dialSingle: QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd:/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd +0ms
  libp2p connecting to discovered peer +7ms
  libp2p:switch:dial starting dial queue to QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3 +7ms
  libp2p:connection-manager QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv: connected to QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3 +6ms
  libp2p:connection-manager checking limit of maxPeers. current value: 8 of 500 +0ms
  libp2p:connection-manager checking protocol limit. current value of ip4 is 8 +0ms
  libp2p:connection-manager checking protocol limit. current value of tcp is 8 +0ms
  libp2p:connection-manager checking protocol limit. current value of ipfs is 8 +1ms
  libp2p:connection-manager checking protocol limit. current value of ip6 is 7 +0ms
  libp2p:conn:out:QmSF16jD dialing QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3 +0ms
  libp2p:conn:out:QmSF16jD dialing transport TCP +1ms
  libp2p:switch:transport dialing TCP [ '/ip4/178.62.61.185/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3',
  '/ip6/2a03:b0c0:1:d0::e7:1/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3' ] +9ms
  libp2p:switch:dialer dialMany:start +8ms
  libp2p:switch:dialer dialSingle: QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3:/ip4/178.62.61.185/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3 +0ms
  libp2p connecting to discovered peer +8ms
  libp2p:switch:dial starting dial queue to QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx +8ms
  libp2p:connection-manager QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv: connected to QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx +8ms
  libp2p:connection-manager checking limit of maxPeers. current value: 9 of 500 +1ms
  libp2p:connection-manager checking protocol limit. current value of ip4 is 9 +0ms
  libp2p:connection-manager checking protocol limit. current value of tcp is 9 +0ms
  libp2p:connection-manager checking protocol limit. current value of ipfs is 9 +0ms
  libp2p:connection-manager checking protocol limit. current value of ip6 is 8 +0ms
  libp2p:conn:out:QmSF16jD dialing QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx +0ms
  libp2p:conn:out:QmSF16jD dialing transport TCP +2ms
  libp2p:switch:transport dialing TCP [ '/ip4/104.236.151.122/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx',
  '/ip6/2604:a880:1:20::1d9:6001/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx' ] +9ms
  libp2p:switch:dialer dialMany:start +9ms
  libp2p:switch:dialer dialSingle: QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx:/ip4/104.236.151.122/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx +0ms
  libp2p connecting to discovered peer +9ms
  libp2p:switch:dial starting dial queue to QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic +9ms
  libp2p:connection-manager QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv: connected to QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic +8ms
  libp2p:connection-manager checking limit of maxPeers. current value: 10 of 500 +0ms
  libp2p:connection-manager checking protocol limit. current value of dns4 is 1 +0ms
  libp2p:connection-manager checking protocol limit. current value of tcp is 10 +0ms
  libp2p:connection-manager checking protocol limit. current value of wss is 1 +0ms
  libp2p:connection-manager checking protocol limit. current value of ipfs is 10 +0ms
  libp2p:conn:out:QmSF16jD dialing QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic +0ms
  libp2p:conn:out:QmSF16jD dialing transport WebSockets +1ms
  libp2p:switch:transport dialing WebSockets [ '/dns4/node0.preload.ipfs.io/tcp/443/wss/ipfs/QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic' ] +4ms
  libp2p:switch:dialer dialMany:start +4ms
  libp2p:switch:dialer dialSingle: QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic:/dns4/node0.preload.ipfs.io/tcp/443/wss/ipfs/QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic +1ms
  libp2p connecting to discovered peer +5ms
  libp2p:switch:dial starting dial queue to Qmbut9Ywz9YEDrz8ySBSgWyJk41Uvm2QJPhwDJzJyGFsD6 +5ms
  libp2p:connection-manager QmSF16jD2bHfCQUgjdoakDP89BoBpygX33geTkSuVb2vsv: connected to Qmbut9Ywz9YEDrz8ySBSgWyJk41Uvm2QJPhwDJzJyGFsD6 +4ms
  libp2p:connection-manager checking limit of maxPeers. current value: 11 of 500 +0ms
  libp2p:connection-manager checking protocol limit. current value of dns4 is 2 +0ms
  libp2p:connection-manager checking protocol limit. current value of tcp is 11 +0ms
  libp2p:connection-manager checking protocol limit. current value of wss is 2 +0ms
  libp2p:connection-manager checking protocol limit. current value of ipfs is 11 +1ms
  libp2p:conn:out:QmSF16jD dialing Qmbut9Ywz9YEDrz8ySBSgWyJk41Uvm2QJPhwDJzJyGFsD6 +0ms
  libp2p:conn:out:QmSF16jD dialing transport WebSockets +0ms
  libp2p:switch:transport dialing WebSockets [ '/dns4/node1.preload.ipfs.io/tcp/443/wss/ipfs/Qmbut9Ywz9YEDrz8ySBSgWyJk41Uvm2QJPhwDJzJyGFsD6' ] +4ms
  libp2p:switch:dialer dialMany:start +3ms
  libp2p:switch:dialer dialSingle: Qmbut9Ywz9YEDrz8ySBSgWyJk41Uvm2QJPhwDJzJyGFsD6:/dns4/node1.preload.ipfs.io/tcp/443/wss/ipfs/Qmbut9Ywz9YEDrz8ySBSgWyJk41Uvm2QJPhwDJzJyGFsD6 +1ms
  ipfs:mfs:utils:with-mfs-root Fetched MFS root QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn +0ms
  libp2p:mdns responding to query +123ms
  libp2p:switch:dialer:queue work:start +0ms
  libp2p:tcp:dial Connecting to 4001 104.236.176.52 +0ms
  libp2p:switch:dialer:queue work:start +2ms
  libp2p:tcp:dial Connecting to 4001 104.131.131.82 +1ms
  libp2p:switch:dialer:queue work:start +1ms
  libp2p:tcp:dial Connecting to 4001 104.236.179.241 +1ms
  libp2p:switch:dialer:queue work:start +0ms
  libp2p:tcp:dial Connecting to 4001 162.243.248.213 +0ms
  libp2p:switch:dialer:queue work:start +1ms
  libp2p:tcp:dial Connecting to 4001 128.199.219.111 +1ms
  libp2p:switch:dialer:queue work:start +0ms
  libp2p:tcp:dial Connecting to 4001 104.236.76.40 +0ms
  libp2p:switch:dialer:queue work:start +1ms
  libp2p:tcp:dial Connecting to 4001 178.62.158.247 +1ms
  libp2p:switch:dialer:queue work:start +0ms
  libp2p:tcp:dial Connecting to 4001 178.62.61.185 +0ms
  libp2p:switch:dialer:queue work:start +1ms
  libp2p:tcp:dial Connecting to 4001 104.236.151.122 +1ms
  libp2p:switch:dialer:queue work:start +0ms
  libp2p:websockets:dialer dialing wss://node0.preload.ipfs.io:443/ipfs/QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic +0ms
  libp2p:switch:dialer:queue work:start +19ms
  libp2p:websockets:dialer dialing wss://node1.preload.ipfs.io:443/ipfs/Qmbut9Ywz9YEDrz8ySBSgWyJk41Uvm2QJPhwDJzJyGFsD6 +19ms
  ipfs:mfs:utils:load-node Loading DAGNode for child QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn +0ms
  ipfs:mfs:stat Stats for / { hash: 'QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn',
  size: 0,
  cumulativeSize: 4,
  blocks: 0,
  type: 'directory',
  local: undefined,
  sizeLocal: undefined,
  withLocality: false } +124ms
  ipfs:mfs:lock Read operation callback invoked +124ms
  ipfs:mfs:lock Finished read operation +0ms
  ipfs:mfs-preload monitoring MFS root QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn +0ms
  ipfs:state -> running +320ms
  ipfs booted +320ms
  ipfs:cli Error: A metric with the name nodejs_gc_runs_total has already been registered.
  ipfs:cli     at Registry.registerMetric (/usr/src/app/node_modules/prom-client/lib/registry.js:79:10)
  ipfs:cli     at Counter.config.registers.forEach.registryInstance (/usr/src/app/node_modules/prom-client/lib/counter.js:80:21)
  ipfs:cli     at Array.forEach (<anonymous>)
  ipfs:cli     at new Counter (/usr/src/app/node_modules/prom-client/lib/counter.js:79:20)
  ipfs:cli     at module.exports (/usr/src/app/node_modules/prometheus-gc-stats/index.js:33:19)
  ipfs:cli     at new HttpApi (/usr/src/app/src/http/index.js:55:7)
  ipfs:cli     at Daemon.start (/usr/src/app/src/cli/daemon.js:73:21) +0ms
A metric with the name nodejs_gc_runs_total has already been registered.
```

**Comment by rdig** [comment]
This seems to be because of the `IPFS_MONITORING` env var being set

I know this doesn't solve the root of this problem, but removing that line from the `Dockerfile` allows your image to run

**Comment by achingbrain** [comment]
I think this is because prometheus metrics are set up [by the daemon](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/src/cli/daemon.js#L18-L25) and then again [by the http api](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/src/http/index.js#L49-L560).

Given that the http api is only run by the daemon this seems a little unnecessary.
