### ISSUE TITLE
TypeError: Expected a value of type `undefined` for `ipld` but received `{}`.

### ISSUE THREAD

**Issue by Jonybang** [ipfs/js-ipfs#2031]
- **Version**: 0.35.0
- **Platform**: Darwin mac.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

#### Description: Error on trying to pass ipld option as described in documentation
```
TypeError: Expected a value of type `undefined` for `ipld` but received `{}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/src/superstruct.js:78:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:47:22)
      at Object.<anonymous> (components/storage/js-ipfs/index.ts:22:18)
      at step (components/storage/js-ipfs/index.ts:44:23)
      at Object.next (components/storage/js-ipfs/index.ts:25:53)

```

#### Steps to reproduce the error:
```
const IPFS = require('ipfs');
const node = new IPFS({
        ipld: { }
    });
```

**Comment by alanshaw** [comment]
Thanks for reporting, any chance you could send a PR to fix this up for us @Jonybang?

**Comment by Jonybang** [comment]
@alanshaw i think i could. I will try
