### ISSUE TITLE
Object API breaks with small nodes and raw leaves

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#2084]
Adding content with CID version 1 forces raw leaves. For data that is small enough to fit in a single chunk you'll get back a "raw" CID, which IPLD resolves to a Buffer.

https://cid.ipfs.io/#bafkreiae3rrggi2h6v6cvfwj7ugqdkourqhkdasxfopme67sbojl34pv7u

The object API breaks when this happens. e.g.

```console
$ echo 'hiya' | jsipfs add --cid-version=1
added bafkreiae3rrggi2h6v6cvfwj7ugqdkourqhkdasxfopme67sbojl34pv7u bafkreiae3rrggi2h6v6cvfwj7ugqdkourqhkdasxfopme67sbojl34pv7u

$ jsipfs object get bafkreiae3rrggi2h6v6cvfwj7ugqdkourqhkdasxfopme67sbojl34pv7u
Cannot read property 'map' of undefined

$ jsipfs object stat bafkreiae3rrggi2h6v6cvfwj7ugqdkourqhkdasxfopme67sbojl34pv7u
TypeError: Cannot read property 'reduce' of undefined
    at waterfall (/Users/alan/Code/protocol-labs/js-ipfs/src/core/components/object.js:374:46)
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/async/internal/once.js:12:16
    at next (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/async/waterfall.js:21:29)
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/async/internal/onlyOnce.js:12:16
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/async/internal/parallel.js:39:9
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/async/internal/once.js:12:16
    at iterateeCallback (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/async/internal/eachOfLimit.js:48:24)
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/async/internal/onlyOnce.js:12:16
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/async/internal/parallel.js:36:13
    at dagPB.util.cid.then (/Users/alan/Code/protocol-labs/js-ipfs/src/core/components/object.js:364:30)
```

**Comment by Prabhakar-Poudel** [comment]
![ipfsobjectapi](https://user-images.githubusercontent.com/20899846/58382305-506c6f00-7fe6-11e9-9049-726041c739ec.png)

@alanshaw 
go ipfs returns `Error: expected protobuf dag node`, when doing `object get`.
and returns an expected result for `object stat`, as seen above.

**Comment by GavinDmello** [comment]
@alanshaw @lidel 
I tried getting to the root of the `object get` issue. It seems that `nodeJSON.links` seems to be undefined at https://github.com/ipfs/js-ipfs/blob/master/src/http/api/resources/object.js#L101. 

Perhaps, we should return an empty links array if `nodeJSON.links` is undefined?

**Comment by lidel** [comment]
@GavinDmello  The code you linked indeed does not support DAGs without `.links`, but there is a reason behind that:

`node` object  returned by `ipfs.object.get` comes from [js-ipld/src/index.js#L124-L135](https://github.com/ipld/js-ipld/blob/e74b6e0b63e9cc1d0d0f5b2f92cb4db3b7f64224/src/index.js#L124-L135). As you can see [here](https://github.com/ipld/js-ipld/blob/e74b6e0b63e9cc1d0d0f5b2f92cb4db3b7f64224/src/index.js#L397) the deserialized object can be `dag-pb`, `dag-cbor` or `raw` (or something else, if a custom codec is added).

The problem: `ipfs object` APIs were created to operate on unixfs (filesystem abstraction) in times when everything was `dag-pb`.

I think a way to clean this up for now would be to do what go-ipfs does:
- Detect missing  `.links` and throw/return `Error: expected protobuf dag node` to the console

In the future we can discuss adding support for `dag-cbor`-based [unixfs-v2/SPEC.md](https://github.com/ipfs/unixfs-v2/blob/master/SPEC.md), or something more generic.

**Comment by GavinDmello** [comment]
@lidel Thanks!

I'll assemble a pull request with the change you mentioned.

**Comment by richardschneider** [comment]
In [net-ipfs-engine](https://github.com/richardschneider/net-ipfs-engine/issues/135), a non-protobuf dag node will always return 0 links instead of throwing an error.  This makes the caller code easier to write.

**Comment by lidel** [comment]
@richardschneider  indeed, we probably should make that change later, in separate PRs to JS and GO + add [interop tests](https://github.com/ipfs/interop) for `objects.*` commands against non `dag-pb` nodes to ensure implementations do the same thing.

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

Closing as the Object API is deprecated and has been removed in Helia.
