### ISSUE TITLE
jsipfs init failed

### ISSUE THREAD

**Issue by suzakinishi** [ipfs/js-ipfs#2122]
- **Version**:0.36.2
- **Platform**:x64/liinux
- **Subsystem**:

#### Description:I install the jsipfs successfully with'npm install ipfs --global'. but when i run jsipfs init , it failed as follow.
```shell
$jsipfs init
initializing ipfs node at /path/to/ipfsrepo
Unexpected token *
```
then i run ' jsipfs' 
```shell
$jsipfs
Not enough non-option arguments: got 0, need at least 1
jsipfs <command>

Commands:
  jsipfs add [file...]            Add a file to IPFS using the UnixFS data
                                  format
  jsipfs bitswap <command>        Interact with the bitswap agent.
  jsipfs block <command>          Manipulate raw IPFS blocks.
  jsipfs bootstrap <command>      Show or edit the list of bootstrap peers.
  jsipfs cat <ipfsPath>           Fetch and cat an IPFS path referencing a file
  jsipfs cid <command>            Convert, format and discover properties of
                                  CIDs.
  jsipfs commands                 List all available commands
  jsipfs config <key> [value]     Get and set IPFS config values
  jsipfs daemon                   Start a long-running daemon process
  jsipfs dag <command>            Interact with ipld dag objects.
  jsipfs dht <command>            Issue commands directly through the DHT.
  jsipfs dns <domain>             Resolve DNS links
  jsipfs file <command>           Interact with IPFS objects representing Unix
                                  filesystems.
  jsipfs get <ipfsPath>           Fetch a file or directory with files
                                  references from an IPFS Path
  jsipfs id                       Shows IPFS Node ID info
  jsipfs init [config] [options]  Initialize a local IPFS node
  jsipfs key                      Manage your keys
  jsipfs ls <key>                 List files for the given directory
  jsipfs name <command>           Publish and resolve IPNS names.
  jsipfs object <command>         Interact with ipfs objects.
  jsipfs pin                      Pin and unpin objects to local storage.
  jsipfs ping <peerId>            Measure the latency of a connection
  jsipfs pubsub <command>         pubsub commands
  jsipfs refs-local               List all local references.
  jsipfs refs <key> [keys..]      List links (references) from an object
  jsipfs repo <command>           Manipulate the IPFS repo.
  jsipfs resolve <name>           Resolve the value of names to IPFS
  jsipfs shutdown                 Shut down the ipfs daemon
  jsipfs stats <command>          Query IPFS statistics.
  jsipfs swarm <command>          Swarm inspection tool.
  jsipfs version                  Shows IPFS version information
  jsipfs completion               generate completion script
  jsipfs files <command>          Operations over mfs files (ls, mkdir, rm, etc)

Options:
  --version  Show version number                                       [boolean]
  --silent   Write no output                          [boolean] [default: false]
  --pass     Pass phrase for the keys                     [string] [default: ""]
  --help     Show help                                                 [boolean]

ipfs uses a repository in the local file system. By default, the repo is located
at ~/.jsipfs. To change the repo location, set the $IPFS_PATH environment
variable:

export IPFS_PATH=/path/to/ipfsrepo
TypeError: cli.parse(...).then(...).catch(...).finally is not a function
    at main (/home/username/.npm-global/lib/node_modules/ipfs/src/cli/bin.js:60:13)
    at Object.<anonymous> (/home/username/.npm-global/lib/node_modules/ipfs/src/cli/bin.js:74:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
TypeError: cli.parse(...).then(...).catch(...).finally is not a function
    at main (/home/username/.npm-global/lib/node_modules/ipfs/src/cli/bin.js:60:13)
    at Object.<anonymous> (/home/username/.npm-global/lib/node_modules/ipfs/src/cli/bin.js:74:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
/home/username/.npm-global/lib/node_modules/ipfs/src/cli/bin.js:8
  throw err
  ^

TypeError: cli.parse(...).then(...).catch(...).finally is not a function
    at main (/home/username/.npm-global/lib/node_modules/ipfs/src/cli/bin.js:60:13)
    at Object.<anonymous> (/home/username/.npm-global/lib/node_modules/ipfs/src/cli/bin.js:74:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
Unexpected token *
```

**Comment by alanshaw** [comment]
Please update to Node.js 10 or 12.
