### ISSUE TITLE
test failure: "recursively resolve _dnslink.ipfs.io" during CLI testing

### ISSUE THREAD

**Issue by vincepmartin** [ipfs/js-ipfs#2516]
- **js-ipfs version: 0.38.0-pre.1-**:
- **Linux 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux**:
- **CLI**:

#### Description:
Running CLI tests via `npm run test:node:cli` causes the following 2 tests to fail.

```
 2 failing

  1) cli
       dns
         daemon off (directly to core)
           recursively resolve _dnslink.ipfs.io dns:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/robotburrito/Code/personal/js-ipfs/test/cli/index.js)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  2) cli
       dns
         daemon on (through http-api)
           recursively resolve _dnslink.ipfs.io dns:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/robotburrito/Code/personal/js-ipfs/test/cli/index.js)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

```
#### Steps to reproduce the error:
Run tests via `npm run test:node:cli` command.

**Comment by vincepmartin** [comment]
I found this, so I may as well try to fix it as it was found while fixing other cli testing problems!

**Comment by whizzzkid** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can follow the migration plan here https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).


This issue has been resolved in Helia! if this does not address your concern please let us know  by reopening this issue before 2023-06-05!
