### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by vporton** [ipfs/js-ipfs#2593]
- **Version**:
- **Platform**: Linux victor-pc 5.3.0-19-generic #20-Ubuntu SMP Fri Oct 18 09:04:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Subsystem**:

#### Steps to reproduce the error:

On Ubuntu 19.10:

```
$ sudo npm -g install ipfs
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
/usr/local/bin/jsipfs -> /usr/local/lib/node_modules/ipfs/src/cli/bin.js

> gc-stats@1.4.0 install /usr/local/lib/node_modules/ipfs/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for gc-stats@1.4.0 and node@10.15.2 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ipfs/node_modules/gc-stats/build' 
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/root/.cache/node-gyp/10.15.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/ipfs/node_modules/gc-stats/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ipfs/node_modules/gc-stats/.node-gyp'
gyp ERR! System Linux 5.3.0-19-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/ipfs/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v64-linux-x64/gcstats.node" "--module_name=gcstats" "--module_path=/usr/local/lib/node_modules/ipfs/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v64-linux-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/local/lib/node_modules/ipfs/node_modules/gc-stats
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/ipfs/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v64-linux-x64/gcstats.node --module_name=gcstats --module_path=/usr/local/lib/node_modules/ipfs/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v64-linux-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ipfs/node_modules/gc-stats/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.3.0-19-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/ipfs/node_modules/gc-stats/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/ipfs/node_modules/gc-stats
node-pre-gyp ERR! node -v v10.15.2
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/ipfs/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v64-linux-x64/gcstats.node --module_name=gcstats --module_path=/usr/local/lib/node_modules/ipfs/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v64-linux-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

> keccak@1.4.0 install /usr/local/lib/node_modules/ipfs/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@1.4.0 rebuild /usr/local/lib/node_modules/ipfs/node_modules/keccak
> node-gyp rebuild

gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/root/.cache/node-gyp/10.15.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/ipfs/node_modules/keccak/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ipfs/node_modules/keccak/.node-gyp'
gyp ERR! System Linux 5.3.0-19-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ipfs/node_modules/keccak
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Keccak bindings compilation fail. Pure JS implementation will be used.

> secp256k1@3.7.1 install /usr/local/lib/node_modules/ipfs/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.7.1 rebuild /usr/local/lib/node_modules/ipfs/node_modules/secp256k1
> node-gyp rebuild

gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/root/.cache/node-gyp/10.15.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/ipfs/node_modules/secp256k1/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ipfs/node_modules/secp256k1/.node-gyp'
gyp ERR! System Linux 5.3.0-19-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ipfs/node_modules/secp256k1
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.7.1 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.7.1 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Secp256k1 bindings compilation fail. Pure JS implementation will be used.

> tiny-secp256k1@1.1.3 install /usr/local/lib/node_modules/ipfs/node_modules/tiny-secp256k1
> npm run build || echo "secp256k1 bindings compilation fail. Pure JS implementation will be used."


> tiny-secp256k1@1.1.3 build /usr/local/lib/node_modules/ipfs/node_modules/tiny-secp256k1
> node-gyp rebuild

gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/root/.cache/node-gyp/10.15.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/ipfs/node_modules/tiny-secp256k1/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ipfs/node_modules/tiny-secp256k1/.node-gyp'
gyp ERR! System Linux 5.3.0-19-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ipfs/node_modules/tiny-secp256k1
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.1.3 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tiny-secp256k1@1.1.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
secp256k1 bindings compilation fail. Pure JS implementation will be used.

> ursa-optional@0.10.1 install /usr/local/lib/node_modules/ipfs/node_modules/ursa-optional
> node rebuild.js

ursaNative bindings compilation fail. This is not an issue. Modules that depend on it will use fallbacks.
fs.js:115
    throw err;
    ^

Error: EACCES: permission denied, open './stdout.log'
    at Object.openSync (fs.js:439:3)
    at Object.writeFileSync (fs.js:1190:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/ipfs/node_modules/ursa-optional/rebuild.js:13:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gc-stats@1.4.0 (node_modules/ipfs/node_modules/gc-stats):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gc-stats@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa-optional@0.10.1 install: `node rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa-optional@0.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-10T19_54_39_359Z-debug.log
```

See the errors in the output in the next comment.

**Comment by vporton** [comment]
`/root/.npm/_logs/2019-11-10T19_54_39_359Z-debug.log` attached.
[2019-11-10T19_54_39_359Z-debug.log](https://github.com/ipfs/js-ipfs/files/3828934/2019-11-10T19_54_39_359Z-debug.log)

**Comment by achingbrain** [comment]
If you’re using sudo with npm install you may need to use the —unsafe-perm flag, otherwise you get this sort of error.

There’s no requirement to install or run IPFS as root though, it doesn’t require any special permissions.
