### ISSUE TITLE
I can't list the files added to my browser node

### ISSUE THREAD

**Issue by ratsclub** [ipfs/js-ipfs#2596]
- **Version**: 0.39.0
- **Platform**: Brave Version 0.70.123 Chromium: 78.0.3904.97 (Official Build) (64-bit)
- **Subsystem**:

#### Steps to reproduce the error:

```js
const path = '/ipfs/QmcpcDQWFqLgz1UfK5PTER3XV7jSiSB4rX9k55N1wA6hVu' // my node id

// i've tried
await this.ipfs.get(path);
await this.ipfs.ls(path);
await this.ipfs.files.ls(path);
```

All of the commands return me this error:

```
zone-evergreen.js:651 Unhandled Promise rejection: No content routers available ; Zone: <root> ; Task: null ; Value: Error: No content routers available
    at Function.<anonymous> (content-routing.js:39)
    at index.js:41
    at new ZoneAwarePromise (zone-evergreen.js:876)
    at Object.findProviders (index.js:35)
    at Network.findProviders (network.js:103)
    at Network.findAndConnect (network.js:119)
    at Bitswap.getMany (index.js:225)
    at async Bitswap.get (index.js:179)
    at async IPLDResolver.get (index.js:131)
    at async unixFsResolver (index.js:23) Error: No content routers available
    at Function.<anonymous> (http://localhost:4200/vendor.js:244813:33)
    at http://localhost:4200/vendor.js:268286:20
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:4143:29)
    at Object.findProviders (http://localhost:4200/vendor.js:268280:16)
    at Network.findProviders (http://localhost:4200/vendor.js:132078:39)
    at Network.findAndConnect (http://localhost:4200/vendor.js:132094:30)
    at Bitswap.getMany (http://localhost:4200/vendor.js:131837:22)
    at async Bitswap.get (http://localhost:4200/vendor.js:131791:22)
    at async IPLDResolver.get (http://localhost:4200/vendor.js:157543:19)
    at async unixFsResolver (http://localhost:4200/vendor.js:138032:16)
```

**Comment by alanshaw** [comment]
@ratsclub what is the value of `nodeId` in your example?

**Comment by ratsclub** [comment]
Sorry, I fixed the example,

**Comment by alanshaw** [comment]
...and would you mind sharing your node configuration? i.e. the constructor options you're using to create the instance.

The title says "I can't list the files added to my browser node" - How did you add these files to your node? Can I see the code and the files you added?

Is this a web application that's running on a domain? Did the domain name change?

Ideally if you have a runnable example that demonstrates the issue I can look into it further.

**Comment by alanshaw** [comment]
ping @ratsclub

**Comment by ratsclub** [comment]
@alanshaw Sorry, I'm out of time to reproduce this right now. I'm sorry. I really appreciate the attention you gave to me.
