### ISSUE TITLE
for await (const part of multipart(request)) {} : Unexpected reserved word

### ISSUE THREAD

**Issue by Thisisjuke** [ipfs/js-ipfs#2598]
- **Version**: 0.39.0
- **Platform**:  Linux de366aabd7eb 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 GNU/Linux

#### Description:

Nothing except 'yarn add ipfs', then when launching my docker.
I've got this error :

```
 (node:77) UnhandledPromiseRejectionWarning: /home/node/app/node_modules/ipfs/src/http/api/resources/object.js:132
     for await (const part of multipart(request)) {
        ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Module._compile (/home/node/app/node_modules/pirates/lib/index.js:99:24)
     at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (/home/node/app/node_modules/pirates/lib/index.js:104:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
```

#### Steps to reproduce the error:

Package JSON : 
```
{
  "name": "node-front",
  "version": "0.0.1",
  "description": "node front",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "test": "jest"
  },
  "type": "module",
  "license": "ISC",
  "dependencies": {
    "boom": "^7.3.0",
    "hapi": "^18.1.0",
    "hapi-router": "^4.0.0", Unexpected reserved word
    "ipfs": "^0.39.0", Unexpected reserved word Unexpected reserved word
    "nodemon": "^1.18.11",
    "uuid": "^3.3.3",
    "videostream": "^3.2.1"
  },
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.4.0",
    "@babel/node": "^7.6.3",
    "@babel/polyfill": "^7.6.0",
    "@babel/preset-env": "^7.4.2",
    "@babel/register": "^7.4.0",
    "babel-plugin-module-resolver": "^3.2.0",
    "jest": "^24.8.0"
  }
}

```

Tried to launch without babel, without nodemon, always the same error. I tried some examples repos, that works.

**Comment by achingbrain** [comment]
Which version of node are you running?  You may need to upgrade.

**Comment by Thisisjuke** [comment]
My docker-compose uses : image: "node:8"

**Comment by achingbrain** [comment]
Please try with Node 10 or above, preferably 12 as it's the LTS version.

**Comment by Thisisjuke** [comment]
Working with Node 12 after updating some dependencies. Thx!
