### ISSUE TITLE
Already piped when connecting to go-ipfs node

### ISSUE THREAD

**Issue by ridenaio** [ipfs/js-ipfs#2720]
- **Version**: 0.40.0
- **Platform**: windows x64

#### Description:

I want to establish connect to my go-ipfs node from js-ipfs using **private ipfs network** and **custom protocol**.

On the one side I use `go-ipfs v0.4.22` as a library and register new protocol as `ipfsHost.SetStreamHandler("/my/protocol/1.0.0", streamHandler)`

On the another side I use js-ipfs and call `dialProtocol`

```
async function start() {
  const node = await IPFS.create({
    libp2p: {
      modules: {
        connProtector: new Protector(
          Buffer.from(
           '/key/swarm/psk/1.0.0/\n/base16/\n9ad6f9bbbbbb2a7308ad8793xxxxxxa974b550cc029ce41aaaaaa0c46db2f530'
          )
        )
      },
      config: {
        dht: {
          enabled: true
        },
        pubsub: {
          enabled: false
        }
      }
    }
  });

  try {
    await node.libp2p.dialProtocol(
      '/ip4/127.0.0.1/tcp/55055/ipfs/QmdnFa1Uw48ScocAZNZhv9n1Q2sGyuFMZEVjqo2eY7EuGf',
      '/my/protocol/1.0.0'
    );
  } catch (e) {
    console.log(e);
  }
}
```

My code fails with this error

```
Error: already piped
    at sink (D:\projects\test-app\node_modules\ipfs\node_modules\pull-pair\index.js:11:13)
    at consume (D:\projects\test-app\node_modules\ipfs\node_modules\pull-defer\sink.js:7:17)
    at consume (D:\projects\test-app\node_modules\ipfs\node_modules\pull-defer\sink.js:7:17)
    at Connection.consume (D:\projects\test-app\node_modules\ipfs\node_modules\pull-defer\sink.js:7:17)
    at pull (D:\projects\test-app\node_modules\ipfs\node_modules\pull-stream\pull.js:43:9)
    at Dialer.handle (D:\projects\test-app\node_modules\ipfs\node_modules\multistream-select\src\dialer\index.js:52:7)
    at ClassIsWrapper._protocolHandshake (D:\projects\test-app\node_modules\ipfs\node_modules\libp2p\src\switch\connection\index.js:464:14)
    at ClassIsWrapper.shake (D:\projects\test-app\node_modules\ipfs\node_modules\libp2p\src\switch\connection\index.js:183:10)
    at createConnectionWithProtocol (D:\projects\test-app\node_modules\ipfs\node_modules\libp2p\src\switch\dialer\queue.js:44:14)
    at ClassIsWrapper.connectionFSM.once (D:\projects\test-app\node_modules\ipfs\node_modules\libp2p\src\switch\dialer\queue.js:270:7)
```

What am i doing wrong?

**Comment by achingbrain** [comment]
`js-libp2p` has undergone an enormous refactoring effort for the last few months that's about to land which may resolve the problem or at least result in a very different stack trace.

You may wish to open an issue on https://github.com/libp2p/js-libp2p

**Comment by achingbrain** [comment]
Could you please try this again with `ipfs@0.41.0-rc.0` and see if the problem persists?  That version of `ipfs` uses the libp2p async/await refactor.

Quite a lot has changed in `libp2p` and `ipfs` though - please see the [migration guide](https://gist.github.com/alanshaw/04b2ddc35a6fff25c040c011ac6acf26) for help upgrading.

**Comment by happy-zhangbo** [comment]
Can I have a look at the whole code? I would like to know about the private network. Which package is new protector

**Comment by achingbrain** [comment]
I'm closing this issue because there's been no response from the original author and the code it invokes has been completely rewritten.

Please re-open if this is still an issue.
