### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by Joncom** [ipfs/js-ipfs#2964]
- **Version**: 0.41.2
- **Platform**: Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

#### Steps to reproduce the error:

```js
'use strict'

const IPFS = require('ipfs')

async function main () {
  const ipfs = await IPFS.create()
  const version = await ipfs.version()
  console.log('Version:', version.version)
}

main()
```

#### Result:

```
Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/QmNRnZU5eBgKWG74YTvCsAC2MhLzBicGoG3Vca3pGeVeDU
Swarm listening on /ip4/192.168.1.92/tcp/4002/p2p/QmNRnZU5eBgKWG74YTvCsAC2MhLzBicGoG3Vca3pGeVeDU
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/QmNRnZU5eBgKWG74YTvCsAC2MhLzBicGoG3Vca3pGeVeDU
Version: 0.41.2
(node:9380) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_ALREADY_FINISHED]: Cannot call end after a stream was finished
    at Socket.Writable.end (_stream_writable.js:647:10)
    at Socket.end (net.js:582:31)
    at Socket.writable.end (/Users/REDACTED/ipfs/node_modules/ipfs/node_modules/stream-to-it/sink.js:24:12)
    at /Users/joncom/REDACTEDde_modules/ipfs/node_modules/libp2p-tcp/src/socket-to-conn.js:82:16
    at new Promise (<anonymous>)
    at Object.close (/Users/REDACTED/ipfs/node_modules/ipfs/node_modules/libp2p-tcp/src/socket-to-conn.js:62:14)
    at Server.<anonymous> (/Users/REDACTED/ipfs/node_modules/ipfs/node_modules/libp2p-tcp/src/listener.js:31:31)
(node:9380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:9380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And then the exact same errors repeat over and over again over time. I'm seeing this sequence of error repeat once every 5 minutes or so.

**Comment by DougAnderson444** [comment]
I am getting the same error:
```bash
$ jsipfs daemon
js-ipfs version:0.43.0
System version x64/win32
Node.js version 13.9.0
...
Daemon is ready
```
... (a bit of use & time, a few minutes or seconds) ...
```
Error [ERR_STREAM_ALREADY_FINISHED]: Cannot call end after a stream was finished

    at Socket.Writable.end (_stream_writable.js:640:10)
    at Socket.end (net.js:588:31)
    at Socket.writable.end (C:\Users\Doug\AppData\Roaming\npm\node_modules\ipfs\
node_modules\stream-to-it\sink.js:24:12)
    at C:\Users\Doug\AppData\Roaming\npm\node_modules\ipfs\node_modules\libp2p-t
cp\src\socket-to-conn.js:82:16
    at new Promise (<anonymous>)
    at Object.close (C:\Users\Doug\AppData\Roaming\npm\node_modules\ipfs\node_mo
dules\libp2p-tcp\src\socket-to-conn.js:62:14)
    at Server.<anonymous> (C:\Users\Doug\AppData\Roaming\npm\node_modules\ipfs\n
ode_modules\libp2p-tcp\src\listener.js:31:31) {
  code: 'ERR_STREAM_ALREADY_FINISHED'
}
```
I am running the daemon, after a bit of use (connect to it as a peer from the go-daemon on same machine) it intermittently shows this error.

**Comment by achingbrain** [comment]
@jacobheun are you able to take a look at this, I can't replicate it locally.

**Comment by jacobheun** [comment]
The issue is that `libp2p-tcp` isn't catching errors when attempting to gracefully close failed inbound connections. Created a fix at https://github.com/libp2p/js-libp2p-tcp/pull/128

**Comment by jacobheun** [comment]
`libp2p-tcp@0.14.5` has been released and should resolve this

**Comment by achingbrain** [comment]
@Joncom @DougAnderson444 can you please try again with the latest js-ipfs (0.43.1), it should get you `libp2p-tcp@0.14.5` which should resolve the problem.
