### ISSUE TITLE
Flaky preload tests

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#3009]
On Windows with Node 10:

```
ipfs:   preload disabled
ipfs:     1) should not preload if disabled
ipfs:   1807 passing (24m)
ipfs:   95 pending
ipfs:   1 failing
ipfs:   1) preload disabled
ipfs:        should not preload if disabled:
ipfs:      Uncaught Error: Timed out waiting for CIDs to be preloaded
ipfs:       at waitFor (test\utils\wait-for.js:18:21)
ipfs:       at process._tickCallback (internal/process/next_tick.js:68:7)
ipfs: 
ipfs: (node:4992) UnhandledPromiseRejectionWarning: Error: Timed out waiting for CIDs to be preloaded
ipfs:     at waitFor (test\utils\wait-for.js:18:21)
ipfs:     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by whizzzkid** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments before 2023-06-05. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).
