### ISSUE TITLE
Ipfs file upload error

### ISSUE THREAD

**Issue by rohail411** [ipfs/js-ipfs#3063]
I'm using IPFS service for file storage. From Node.js application I can initialize IPFS_Node and using this Node upload file.

```js
var ipfs = ipfsClient({
            // the hostname (or ip address) of the endpoint providing the ipfs api
            host: '*****************',
            // the port to connect on
            port: '443',
            // 'api-path': '/api/v0/',
            // the protocol, https for security
            protocol: 'https',
            // provide the jwt within an authorization header
            headers: {
                authorization:
                    'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ**********************'
            }
        });
    for await (const response of ipfs.add(file.buffer)) {
            console.log(response);
            res.json({ response: response, status: 200 });
        }
```

**Ipfs add throws Error Response**
```
HTTPError: Unauthorized

   at Object.errorHandler [as handleError] (C:\Users\Rohail\Documents\GitHub\Artbot_api\node_modules\ipfs-http-client\src\lib\core.js:67:15)        
   at processTicksAndRejections (internal/process/task_queues.js:93:5)
   at Client.fetch (C:\Users\Rohail\Documents\GitHub\Artbot_api\node_modules\ipfs-utils\src\http.js:145:9)
   at Object.add (C:\Users\Rohail\Documents\GitHub\Artbot_api\node_modules\ipfs-http-client\src\add.js:13:17) {
 name: 'HTTPError',
 response: Response {
   size: 0,
   timeout: 0,
   [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
   [Symbol(Response internals)]: {
     url: 'https://api.ipfs.temporal.cloud/api/v0/add?stream-channels=true&progress=false',
     status: 401,
     statusText: 'Unauthorized',
     headers: [Headers],
     counter: 0
   }
 }
}
```

**Comment by achingbrain** [comment]
You're getting a `401 Unauthorized`.  Are you sure your bearer token is correct?

There was a bug in `ipfs-http-client` where it wasn't passing headers correctly that has been fixed - what version are you using?

**Comment by rohail411** [comment]
Yes, My Token is correct.
I'm using this version  of IPFS  "ipfs-http-client": "^44.0.1"

**Comment by rohail411** [comment]
I find issue "ipfs-http-client" version (^44.0.1) cause error when I update to latest version (^44.1.1) error resolved.thanks
