### ISSUE TITLE
Intermittent failures: Returns 400 for request with invalid argument

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#3101]
Following test fails intermittently

```
ipfs:   1 failing
ipfs:   1) HTTP Gateway
ipfs:        returns 400 for request with invalid argument:
ipfs:       AssertionError: expected { Object (raw, headers, ...) } to have property 'statusCode' of 400, but got 500
ipfs:       + expected - actual
ipfs:       -500
ipfs:       +400
ipfs:       
ipfs:       at Context.<anonymous> (test/gateway/index.js:115:25)
ipfs:       at runMicrotasks (<anonymous>)
ipfs:       at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by achingbrain** [comment]
Is this still a problem?

**Comment by Gozala** [comment]
Have not seen those any more
