### ISSUE TITLE
 nodejs ipfs-http-client: invalid 'ipfs ref' path

### ISSUE THREAD

**Issue by peterblockman** [ipfs/js-ipfs#3160]
- **Version**: 

```
await ipfs.version()
{
  version: '0.4.18',
  commit: '',
  repo: '7',
  system: 'arm64/linux',
  golang: 'go1.11.1'
}
```
```
node -v   
v12.14.0
```
```
"ipfs-http-client": "^44.3.0",
```
- **Platform**:

```Linux rockpi 4.4.154-95-rockchip-gd2ab1f26e1b3 #1 SMP Mon Oct 21 06:42:35 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux```
- **Subsystem**:

#### Severity:

High
#### Description:

some other APIs such as `ipfsClient.stats.bw`, `ipfsClient.stats`, `ipfsClient.bitswap`, etc. works well except ` ipfsClient.pin.ls`

#### Steps to reproduce the error:

This 
```
const ipfsHttpClient = require('ipfs-http-client');
const IPFS_URL = 'a host'
const ipfsClient = ipfsHttpClient(IPFS_URL);

 for await (const { cid, type } of ipfsClient.pin.ls()) {
      console.log({ cid, type });
}
```
throws
```
\"HTTPError: invalid 'ipfs ref' path\\n    at Object.errorHandler [as handleError] (/Users/peter/Programming/project/ipfs-dashboard-server/node_modules/ipfs-http-client/src/lib/core.js:67:15)\\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\\n    at async Client.fetch (/Users/peter/Programming/project/ipfs-dashboard-server/node_modules/ipfs-utils/src/http.js:155:9)\\n    at async Object.ls (/Users/peter/Programming/project/ipfs-dashboard-server/node_modules/ipfs-http-client/src/pin/ls.js:16:17)\\n    at async /Users/peter/Programming/project/ipfs-dashboard-server/modules/ipfs_client/generator.js:18:34\\n    at async /Users/peter/Programming/project/ipfs-dashboard-server/components/pinned_file/services.js:78:17\
```

Adding type in options
```
for await (const { cid, type } of ipfsClient.pin.ls({ type: 'indirect' })) {
      console.log({ cid, type });
}
```

results in this error
```
Invalid version, must be a number equal to 1 or 0\n    at Function.validateCID (/Users/peter/Programming/project/ipfs-dashboard-server/node_modules/cids/src/index.js:296:13)\n    at new CID (/Users/peter/Programming/project/ipfs-dashboard-server/node_modules/cids/src/index.js:140:9)\n    at new CID (/Users/peter/Programming/project/ipfs-dashboard-server/node_modules/class-is/index.js:15:17)\n    at Object.ls (/Users/peter/Programming/project/ipfs-dashboard-server/node_modules/ipfs-http-client/src/pin/ls.js:28:20)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /Users/peter/Programming/project/ipfs-dashboard-server/modules/ipfs_client/generator.js:21:34\n    at async /Users/peter/Programming/project/ipfs-dashboard-server/components/pinned_file/services.js:78:17
```

Thank you in advance.

**Comment by achingbrain** [comment]
That `invalid 'ipfs ref' path` error is coming from go-ipfs - what happens when you hit the API endpoint directly?

Adjust the host/port to what's printed after `API server listening on...` during your node startup accordingly:

```console
curl -X POST http://localhost:5001/api/v0/pin/ls
```

**Comment by peterblockman** [comment]
Thank you for the reply. this is the response I got from hitting the API directly. 
```
"Keys": {
    "QmNMC7shku1b12Pt1eTx5LR7ezX1QC9UPCUvM3ndPCY85G": {
      Type: "recursive",
    },
    "QmNMjEjisqc4nySNfdLVGTaMdc1th9yz7wtrqVnALTHUN4": {
      Type: "recursive",
    },
    "QmNRoubWo6YiZjjjkhF1nx1r7WcmfCxpfhzSDoKZrQeYYw": {
      Type: "recursive",
    },
    "QmNT3X8Sos3uNMqs92TJ5uMB2u9WC288cYvNYT1BTLh6mP": {
      Type: "recursive",
    },
    "QmNUNozpEg72JussJA9phmdwQhQgJCnYTRPHyRJRkBnD5B": {
      Type: "recursive",
    },
    "QmNaT3MgZfVy2Ugn5zqhi3uhGxitVPJ3VVfPokiFJLunEB": {
      Type: "recursive",
    },
    "QmNaY7TZNhHmR3UsBfrgLKUqeHxBzHZzoUMaSpiWm7ZMEZ": {
      Type: "recursive",
    },
    "QmNeLrp79ksQb5s2rnW1DafUns13Q9GAEVNT9Pz92ek8XA": {
      Type: "recursive",
    }
    ...
  }```

**Comment by achingbrain** [comment]
Do you still see this problem with the current go-IPFS release?  `v0.4.18` is very old and will stop being able to talk to more up to date peers in the next release or so.

**Comment by achingbrain** [comment]
I'm closing this due to lack of author followup - please reopen if you're still seeing this problem.
