### ISSUE TITLE
js-ipfs 0.47.0 - UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by viventra** [ipfs/js-ipfs#3168]
I migrated my project that uses js-ipfs from 0.43 to 0.47 and started getting a bunch of UnhandledPromiseRejectionWarning messages.

Here's my environment:

```
D:\Viventra\Source\Repos>ver

Microsoft Windows [Version 10.0.18363.900]
```
```
D:\Viventra\Source\Repos\showtime>jsipfs --version
0.47.0
```

```
D:\Viventra\Source\Repos\showtime>node -v
v12.18.2

```

Here's sample code (in file test_ipfs.js) for reproducing the issue:

```
var IPFS = require('ipfs');
ipfsPathExists = async function(ipfs, path) {
        try {
                var foo = await ipfs.files.stat(path);
                return true;
        } catch (err) {
                return false;
        }
}

main = async function () {
        var ipfs = await IPFS.create();
        await ipfs.ready;

        var res = await ipfs.files.ls('/showtime/movies');
        for await(let item of res) {
                console.log(item);
        }

        if(ipfsPathExists(ipfs, '/showtime/movies'))
                console.log('Path exists');
        else
                console.log('Path does not exist');

}

main();
```

IPFS MFS paths previously created. No issues here as reported by js-ipfs CLI.

```
D:\Viventra\Source\Repos\showtime>jsipfs files ls /
showtime

D:\Viventra\Source\Repos\showtime>jsipfs files ls /showtime
movies
permissions
stats
```

Here is the error/warning log:

```
D:\Viventra\Source\Repos\showtime>node test_ipfs.js
Swarm listening on /ip4/192.168.0.3/tcp/4002/p2p/QmPs7jZZbG3xM4L5os18CBh7w6oeowXJxEYPaiPcHvGSjm
Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/QmPs7jZZbG3xM4L5os18CBh7w6oeowXJxEYPaiPcHvGSjm
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/QmPs7jZZbG3xM4L5os18CBh7w6oeowXJxEYPaiPcHvGSjm
Path exists
(node:7384) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'catch' of undefined
    at Peer.attachConnection (D:\Viventra\Source\Repos\showtime\node_modules\ipfs\node_modules\libp2p-pubsub\src\peer.js:107:6)
    at GossipSub._onPeerConnected (D:\Viventra\Source\Repos\showtime\node_modules\ipfs\node_modules\libp2p-pubsub\src\index.js:198:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GossipSub._onPeerConnected (D:\Viventra\Source\Repos\showtime\node_modules\ipfs\node_modules\libp2p-gossipsub\src\pubsub.js:91:5)
(node:7384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7384) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'catch' of undefined
    at Peer.attachConnection (D:\Viventra\Source\Repos\showtime\node_modules\ipfs\node_modules\libp2p-pubsub\src\peer.js:107:6)
    at GossipSub._onPeerConnected (D:\Viventra\Source\Repos\showtime\node_modules\ipfs\node_modules\libp2p-pubsub\src\index.js:198:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GossipSub._onPeerConnected (D:\Viventra\Source\Repos\showtime\node_modules\ipfs\node_modules\libp2p-gossipsub\src\pubsub.js:91:5)
(node:7384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7384) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'catch' of undefined
    at Peer.attachConnection (D:\Viventra\Source\Repos\showtime\node_modules\ipfs\node_modules\libp2p-pubsub\src\peer.js:107:6)
    at GossipSub._onPeerConnected (D:\Viventra\Source\Repos\showtime\node_modules\ipfs\node_modules\libp2p-pubsub\src\index.js:198:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GossipSub._onPeerConnected (D:\Viventra\Source\Repos\showtime\node_modules\ipfs\node_modules\libp2p-gossipsub\src\pubsub.js:91:5)
```

This seems to be happening inside the libp2p-pubsub dependency of js-ipfs on first glance.

How do I get rid of these warning messages? Any help is greatly appreciated. Thank you.

**Comment by viventra** [comment]
I figured out the reason and it is not related to js-ipfs, but NodeJs.

I modified my code to include a .catch() handler and that got rid of the UnhandledPromiseRejectionWarning.

`main().catch(() => {}); 
`
This issue can be closed.
