### ISSUE TITLE
ipfs Installation Error

### ISSUE THREAD

**Issue by rafaelrodriguez342** [ipfs/js-ipfs#3217]
Hello Im having an issue installing ipfs dependency, Im not having this error with the other versions "js-ipfs" and "ipfs-http-client", not sure what is causing it, looks like an error with the require dependencies of this module.
These are the logs of the errors:

```
npm install
npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated @hapi/hapi@18.4.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/ammo@3.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/content@4.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/accept@3.2.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bounce@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/call@5.1.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/catbox@10.2.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/catbox-memory@4.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/heavy@6.2.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/mimos@4.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/podium@3.4.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/somever@2.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/subtext@6.1.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/statehood@6.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/teamwork@3.3.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@16.1.8: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated @hapi/shot@4.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/file@1.0.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/pez@4.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated peer-info@0.17.5: No longer supported for js-libp2p0.28.0 or later
npm WARN deprecated @hapi/pinpoint@1.0.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/formula@1.2.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/wreck@15.1.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/iron@5.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/cryptiles@4.2.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/nigel@3.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/vise@3.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/b64@4.2.1: This version has been deprecated and is no longer supported or maintained

> gc-stats@1.4.0 install E:\bille_web\functions\node_modules\gc-stats
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v72-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for gc-stats@1.4.0 and node@12.16.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'E:\bille_web\functions\node_modules\gc-stats\-e'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\user\.cache\firebase\tools\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\user\\DOWNLO~1\\firebase-tools-instant-win.exe" "C:\\Users\\user\\.cache\\firebase\\tools\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\bille_web\\functions\\node_modules\\gc-stats\\build\\gcstats\\v1.4.0\\Release\\node-v72-win32-x64\\gcstats.node" "--module_name=gcstats" "--module_path=E:\\bille_web\\functions\\node_modules\\gc-stats\\build\\gcstats\\v1.4.0\\Release\\node-v72-win32-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd E:\bille_web\functions\node_modules\gc-stats
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\user\DOWNLO~1\firebase-tools-instant-win.exe C:\Users\user\.cache\firebase\tools\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\bille_web\functions\node_modules\gc-stats\build\gcstats\v1.4.0\Release\node-v72-win32-x64\gcstats.node --module_name=gcstats --module_path=E:\bille_web\functions\node_modules\gc-stats\build\gcstats\v1.4.0\Release\node-v72-win32-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\bille_web\functions\node_modules\gc-stats\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Users\\user\\DOWNLO~1\\firebase-tools-instant-win.exe" "E:\\bille_web\\functions\\node_modules\\gc-stats\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\bille_web\functions\node_modules\gc-stats
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Users\user\DOWNLO~1\firebase-tools-instant-win.exe C:\Users\user\.cache\firebase\tools\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\bille_web\functions\node_modules\gc-stats\build\gcstats\v1.4.0\Release\node-v72-win32-x64\gcstats.node --module_name=gcstats --module_path=E:\bille_web\functions\node_modules\gc-stats\build\gcstats\v1.4.0\Release\node-v72-win32-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)

> bcrypto@5.1.0 install E:\bille_web\functions\node_modules\bcrypto
> node-gyp rebuild


> if not defined npm_config_node_gyp (node "C:\Users\user\.cache\firebase\tools\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\user\.cache\firebase\tools\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
  base58.c
  bech32.c
  cash32.c
  murmur3.c
  aead.c
  chacha20.c
  drbg.c
  dsa.c
  ecc.c
  hash.c
  kdf.c
  poly1305.c
  rsa.c
  salsa20.c
  siphash.c
  util.c
  bcrypto.cc
  mini-gmp.c
  secp256k1.c
  lax_der_parsing.c
  win_delay_load_hook.cc
     Creando biblioteca E:\bille_web\functions\node_modules\bcrypto\build\Release\bcrypto.lib y objeto E:\bille_web\fun
  ctions\node_modules\bcrypto\build\Release\bcrypto.exp
  bcrypto.vcxproj -> E:\bille_web\functions\node_modules\bcrypto\build\Release\\bcrypto.node

> leveldown@5.6.0 install E:\bille_web\functions\node_modules\leveldown
> node-gyp-build


> keccak@3.0.1 install E:\bille_web\functions\node_modules\keccak
> node-gyp-build || exit 0


> secp256k1@4.0.2 install E:\bille_web\functions\node_modules\secp256k1
> node-gyp-build || exit 0


> tiny-secp256k1@1.1.5 install E:\bille_web\functions\node_modules\tiny-secp256k1
> npm run build || echo "secp256k1 bindings compilation fail. Pure JS implementation will be used."


> tiny-secp256k1@1.1.5 build E:\bille_web\functions\node_modules\tiny-secp256k1
> node-gyp rebuild


> if not defined npm_config_node_gyp (node "C:\Users\user\.cache\firebase\tools\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\user\.cache\firebase\tools\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'E:\bille_web\functions\node_modules\tiny-secp256k1\-e'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\user\.cache\firebase\tools\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\user\\DOWNLO~1\\firebase-tools-instant-win.exe" "C:\\Users\\user\\.cache\\firebase\\tools\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\bille_web\functions\node_modules\tiny-secp256k1
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.1.5 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiny-secp256k1@1.1.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-08-08T02_23_48_647Z-debug.log
"secp256k1 bindings compilation fail. Pure JS implementation will be used."

> ursa-optional@0.10.1 install E:\bille_web\functions\node_modules\ursa-optional
> node rebuild.js

ursaNative bindings compilation fail. This is not an issue. Modules that depend on it will use fallbacks.

> protobufjs@6.8.8 postinstall E:\bille_web\functions\node_modules\libp2p-noise\node_modules\protobufjs
> node scripts/postinstall


> level@5.0.1 postinstall E:\bille_web\functions\node_modules\level
> opencollective-postinstall || exit 0

Thank you for using level!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/level/donate

npm WARN libp2p-delegated-content-routing@0.5.0 requires a peer of ipfs-http-client@^44.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN libp2p-delegated-peer-routing@0.5.0 requires a peer of ipfs-http-client@^44.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN prometheus-gc-stats@0.6.2 requires a peer of prom-client@>= 10 < 12 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gc-stats@1.4.0 (node_modules\gc-stats):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gc-stats@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by jacobheun** [comment]
>  Im not having this error with the other versions "js-ipfs" and "ipfs-http-client"

What do you mean by other versions? What version are you trying to install and what version didn't have the issue?

Also, is this actually failing, I don't see the final message from npm install in the logs? The errors you logged are optional dependencies failing due to node-gyp issues on windows, and won't cause a problem using the module.

If you want to get around the node-gyp issue for the optional dependencies, check out the windows instructions at https://github.com/nodejs/node-gyp#on-windows.

**Comment by jacobheun** [comment]
If this is an issue let us know, going to close this for now.
