### ISSUE TITLE
Browser pubsub Firefox workaround not working around?

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#3226]
[This function](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-client/src/pubsub/subscribe.js#L19-L29) claims to start a pubsub subscription moving by sending some data but running the tests with `DEBUG=ipfs*` shows the following:

```console
LOG: '%cipfs-http-client:pubsub:subscribe %cFailed to publish empty message%c +4ms', 'color: #6633CC', 'color: inherit', 'color: #6633CC', HTTPError: argument "data" is required

HTTPError: argument "data" is required

    at Object.errorHandler [as handleError] (file:/Users/alex/Documents/Workspaces/ipfs/js-ipfs/packages/ipfs-http-client/src/lib/core.js:87:15)
    at async Client.fetch (file:/Users/alex/Documents/Workspaces/ipfs/js-ipfs/node_modules/ipfs-utils/src/http.js:153:9)
    at async eval (file:/Users/alex/Documents/Workspaces/ipfs/js-ipfs/packages/ipfs-http-client/src/pubsub/publish.js:22:17)
    at async eval (file:/Users/alex/Documents/Workspaces/ipfs/js-ipfs/packages/ipfs-http-client/src/pubsub/subscribe.js:30:9)
```

So go-IPFS is rejecting the empty message.  Needs more analysis but this workaround may not be working around any more.

**Comment by StationedInTheField** [comment]
```Uncaught (in promise) Error: argument "data" is required
    at main-es2015.a39af3eb25375ecc866b.js:1
    at Object.publish (main-es2015.a39af3eb25375ecc866b.js:1)
    at main-es2015.a39af3eb25375ecc866b.js:1```
+1

**Comment by StationedInTheField** [comment]
```
Uncaught (in promise) Error: argument "data" is required
    at main-es2015.a39af3eb25375ecc866b.js:1
    at Object.publish (main-es2015.a39af3eb25375ecc866b.js:1)
    at main-es2015.a39af3eb25375ecc866b.js:1
```

**Comment by achingbrain** [comment]
@StationedInTheField aside from the error message itself, are you seeing problems with pubsub - dropped messages etc?

**Comment by StationedInTheField** [comment]
I'm still investigating, for 2-3/10 messages are delayed, also between two browsers on the same machine.

**Comment by achingbrain** [comment]
Possibly related: https://github.com/ipfs/js-ipfs/issues/2662

**Comment by achingbrain** [comment]
Closing as this issue is very stale.
