### ISSUE TITLE
error when i try to require ipfs with parse-duration

### ISSUE THREAD

**Issue by josselinchevalay** [ipfs/js-ipfs#3233]
- **Version**: 0.49.0

- **Platform**: #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- **Subsystem**: all system 

#### Description:
i try to use IPFS on my application so i added ipfs on dependencies of my project and try to require.

#### Steps to reproduce the error:
1. `npm -i ipfs`
2. `Const IPFS = require('ipfs')`
3. run your a node js with 2.

my i see that's error : 
```
Error: No valid exports main found for '/home/josselin/src/docker-astroport/ipfs-server/node_modules/parse-duration'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/josselin/src/docker-astroport/ipfs-server/node_modules/ipfs/src/core/utils.js:8:23)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND'
```

**Comment by achingbrain** [comment]
What version of node are you using?

**Comment by josselinchevalay** [comment]
v13.5.0

**Comment by achingbrain** [comment]
Can you try with v12 please? It's the current LTS and the latest one we test with, until we upgrade to the latest Hapi.

**Comment by josselinchevalay** [comment]
ok quick play with nvm 

ipfs@0.49.0 seems work fine with  : 

- 12.18.3 (lts)
- 14.8.0

for 13.5.0 ipfs seems not works i will use lts version thx

**Comment by zoernert** [comment]
Could confirm tht v13.1.0 had same issue - could be solved with up/downgrade of NodeJS
