### ISSUE TITLE
#meetings = null; SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by Jonybang** [ipfs/js-ipfs#3303]
- **Version**:
js-ipfs repo, latest commit `8699cba5c7c5d57f1af04eee1031868d2885bc0e`

- **Platform**:
Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- **Subsystem**:
node v10.22.0, ipfs package inside repo

#### Severity:
High - Aegir build failed

#### Description:
I'm cloned the repo and tried to build application, but received error:
```
> ipfs@0.50.2 build /home/jonybang/workspace/tests/js-ipfs/packages/ipfs
> aegir build

/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/@hapi/teamwork/lib/index.js:8
    #meetings = null;
    ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/@hapi/hapi/lib/server.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/@hapi/teamwork/lib/index.js:8
    #meetings = null;
    ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/v8-compile-cache/v8-compile-cache.js:242:18)
    at Module._compile (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/@hapi/hapi/lib/server.js:6:18)
    at Module._compile (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/@hapi/hapi/lib/index.js:3:16)
    at Module._compile (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/ipfsd-ctl/src/endpoint/server.js:3:14)
    at Module._compile (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
70% building 373/407 modules 34 active .../lib/index.js??ref--4-oneOf-1!/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/ipld-dag-pb/src/dag-node/toDagLink.jsModuleNotFoundError: Module not found: Error: Can't resolve 'stream' in '/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/cbor/lib'
    at factory.create (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/webpack/lib/Compilation.js:925:10)
    at factory (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
    at resolver (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/neo-async/async.js:2830:7
    at /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
    at hook.callAsync (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
    at hook.callAsync (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
    at hook.callAsync (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn24 (eval at create (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at resolver.doResolve (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40)
    at hook.callAsync (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at args (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/enhanced-resolve/lib/forEachBail.js:30:14)
    at hook.callAsync (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
    at hook.callAsync (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
resolve 'stream' in '/home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/cbor/lib'
  Parsed request is a module
  using description file: /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/cbor/package.json (relative path: ./lib)
    resolve as module
      /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/cbor/lib/node_modules doesn't exist or is not a directory
      /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/cbor/node_modules doesn't exist or is not a directory
      /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/node_modules doesn't exist or is not a directory
      /home/jonybang/workspace/tests/js-ipfs/packages/node_modules doesn't exist or is not a directory
      /home/jonybang/workspace/tests/js-ipfs/node_modules doesn't exist or is not a directory
      /home/jonybang/workspace/tests/node_modules doesn't exist or is not a directory
      /home/jonybang/workspace/node_modules doesn't exist or is not a directory
      /home/jonybang/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules
        using description file: /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/package.json (relative path: ./node_modules)
          using description file: /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/package.json (relative path: ./node_modules/stream)
            no extension
              /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/stream doesn't exist
            .wasm
              /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/stream.wasm doesn't exist
            .mjs
              /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/stream.mjs doesn't exist
            .js
              /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/stream.js doesn't exist
            .json
              /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/stream.json doesn't exist
            .ts
              /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/stream.ts doesn't exist
            .d.ts
              /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/stream.d.ts doesn't exist
            as directory
              /home/jonybang/workspace/tests/js-ipfs/packages/ipfs/node_modules/stream doesn't exist

```
#### Steps to reproduce the error:
```
git clone git@github.com:ipfs/js-ipfs.git
cd js-ipfs/packages/ipfs
npm i
npm run build
```

**Comment by achingbrain** [comment]
Please upgrade to node 12 or 14, Hapi dropped support for node 10 a while back.

**Comment by achingbrain** [comment]
Did you try upgrading node? Did it solve the problem if so?

**Comment by defi-dev** [comment]
yes, it's working now, thank you

**Comment by Jonybang** [comment]
It works now, thanks

**Comment by spdebbarma** [comment]
I'm getting this error on Node v16.13.2

**Comment by gaspan** [comment]
> I'm getting this error on Node v16.13.2

same  here
