### ISSUE TITLE
ipfs.init(): TypeError: callback is not a function

### ISSUE THREAD

**Issue by kenshyx** [ipfs/js-ipfs#349]
If I try to run `init()` without specifying some options the callback is saved on `opts`.
```
TypeError: callback is not a function
    at node_modules/ipfs/lib/core/ipfs/init.js:29:16
    at node_modules/fs-blob-store/index.js:65:5
    at FSReqWrap.oncomplete (fs.js:117:15)
```

**Comment by diasdavid** [comment]
Thank you @kenshyx , fixed on https://github.com/ipfs/js-ipfs/pull/416
