### ISSUE TITLE
dht.findProvs: TypeError: key.toBaseEncodedString is not a function

### ISSUE THREAD

**Issue by tymmesyde** [ipfs/js-ipfs#3502]
- **Version**: 0.53.2

- **Platform**: Windows 10

- **Subsystem**:

#### Description:
Unable to get providers from dht with a string cid.

#### Steps to reproduce the error:
Code:
```js
const providers = await all(this.ipfs.dht.findProvs(`Qm...`));
console.log(providers);
```
Error:
`TypeError: key.toBaseEncodedString is not a function`

**Comment by achingbrain** [comment]
The `cid` argument to `ipfs.dht.findProvs` should be of the [CID](https://www.npmjs.com/package/cids) type and not a string: https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/DHT.md#ipfsdhtfindprovscid-options

**Comment by jacobheun** [comment]
Closing as the resolution has been suggested.

**Comment by TheDiscordian** [comment]
Requesting re-open, for 2 reasons.

1. The linked doc uses a string in the example (`ipfs.dht.findProvs('QmdPAhQRxrDKqkGPvQzBvjYe3kU8kiEEAd2J6ETEamKAD9')`)
2. Not using a string produces the exact same error.

```js
const IPFS = require('ipfs-core');
const CID = require('cids');
 
async function run() {
	const node = await IPFS.create({
		repo: 'ok' + Math.random(), // random so we get a new peerid every time, useful for testing
		libp2p: {
			config: {
				dht: {
					enabled: true
				}
			}
		}
	});

	const { cid } = await node.add('Hello world');
	
	console.log(cid);
	// CID(QmNRCQWfgze6AbBCaT1rkrkV5tJ2aP4oTNPb5JZcXYywve)
	console.log(CID.isCID(cid));
	// true

	const providers = node.dht.findProvs(cid);
	
	for await (const provider of providers) {
		console.log(provider.id.toString());
	}
}
 
run();
```

```
[user@TheDesktop DHT]$ node index.js
generating 2048-bit (rsa only) RSA keypair...
to get started, enter:

        jsipfs cat /ipfs/QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr/readme

Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/QmVG4ZKiXgw1cU8VJ4fAj5P5aF45RAsE2tnskmghXNs2J7
Swarm listening on /ip4/<REDACTED>/tcp/4002/p2p/QmVG4ZKiXgw1cU8VJ4fAj5P5aF45RAsE2tnskmghXNs2J7
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/QmVG4ZKiXgw1cU8VJ4fAj5P5aF45RAsE2tnskmghXNs2J7
CID(QmNRCQWfgze6AbBCaT1rkrkV5tJ2aP4oTNPb5JZcXYywve)
true
/home/user/Programming/JS/Node/DHT/node_modules/libp2p-kad-dht/src/content-routing/index.js:79
      dht._log('findProviders %s', key.toBaseEncodedString())
                                       ^

TypeError: key.toBaseEncodedString is not a function
    at Object.findProviders (/home/user/Programming/JS/Node/DHT/node_modules/libp2p-kad-dht/src/content-routing/index.js:79:40)
    at findProviders.next (<anonymous>)
    at KadDHT.findProviders (/home/user/Programming/JS/Node/DHT/node_modules/libp2p-kad-dht/src/index.js:315:22)
    at findProviders.next (<anonymous>)
    at findProvs (/home/user/Programming/JS/Node/DHT/node_modules/ipfs-core/src/components/dht.js:67:24)
    at async run (/home/user/Programming/JS/Node/DHT/index.js:24:19)
```

**Comment by autonome** [comment]
@achingbrain ^ should reopen or file new issues?

**Comment by PyKestrel** [comment]
I have the same issue currently even after creating a CID object.

**Comment by tarunbatra** [comment]
I am facing this issue as well with the `dht.findProvs` method. I am open to create a PR for this and it would help if someone can point me at places to look. @achingbrain @lidel

**Comment by tarunbatra** [comment]
This issue was resolved for me when I installed the latest IPFS. I suspect it was resolved due to [this change](https://github.com/libp2p/js-libp2p-kad-dht/commit/71952820ef3f737204b7a615db69ae680ef652a8#diff-38171968c0a0b8223fb6df428b7553271a854160e8db4c112a49ac28a5a256d0L79) in [ipfs/libp2p-kad-dht](https://github.com/libp2p/js-libp2p-kad-dht).

However this has led to other errors (`Error: Unknown type, must be binary type`) for me which I think are not suitable for this issue.

**Comment by jarrillaga** [comment]
Hello guys, how are you?

I'm facing the exact same issue, this is my code:

const ipfs = await create();
const cid = new CID('QmdKcc3ETD4Xy2f8fJZSNvtfcBfk5sxyMqQthSGn6wEXe1')
const providers = ipfs.dht.findProvs(cid);

for await (const provider of providers) {
    console.log(provider)
}

Error: throw Error('Unknown type, must be binary type')

As you can see, I'm sending the CID as an object instance and not the string. 

I really need if someone help me with this?

Thanks in advance.
