### ISSUE TITLE
Following the core-api/FILES I get this error: "globSource is not a function"

### ISSUE THREAD

**Issue by raphael10-collab** [ipfs/js-ipfs#3519]
In an Electron-Typescript app following this example: https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#importing-files-from-the-file-system I get this error: "globSource is not a function"

this is the code :  

    import Ipfs from 'ipfs';
    const { globSource } = Ipfs;

    const ops = async () => {
      const node = await Ipfs.create({ repo: String(Math.random() + Date.now()) });

      const addOptions = {
        pin: true,
        wrapWithDirectory: true,
        timeout: 10000
      };
      for await (const file of node.addAll(globSource('/home/marco/Downloads', globSourceOptions), addOptions)) {
        console.log(file);
      }
    }
    ops();

- node version: v14.5.0
- OS: Ubuntu 18.04.4 Desktop
- electron: 11.2.1

**Comment by raphael10-collab** [comment]
As suggested by a kind fellow in https://discuss.ipfs.io/ I tried to move the ipfs-related code to the main process main.ts .

With this webpack configuration:

/tools/webpack/webpack.main.js  : 

    module.exports = {
      /**
       * This is the main entry point for your application, it's the first file
       * that runs in the main process.
       */
      entry: ['./src/main.ts'],
      // Put your normal webpack config below here
      module: {
        rules: require('./webpack.rules'),
      },
      resolve: {
        extensions: ['.js', '.ts', '.jsx', '.tsx', '.css', '.json'],
        alias: require('./webpack.aliases'),
      },
      // https://github.com/electron/electron/issues/9920
      //target: 'electron-renderer'
      target: 'electron-main'
    };


/tools/webpack/webpack.renderer.js :  

/* eslint-disable @typescript-eslint/no-var-requires */
    const rules = require('./webpack.rules');
    const plugins = require('./webpack.plugins');
    const aliases = require('./webpack.aliases');

    module.exports = {
      // https://github.com/electron/electron/issues/9920
      target: 'electron-renderer',
      module: {
        rules,
      },
      plugins: plugins,
      resolve: {
        extensions: ['.js', '.ts', '.jsx', '.tsx', '.css'],
        alias: {
          // React Hot Loader Patch
          'react-dom': '@hot-loader/react-dom',
          // Custom Aliases
          ...aliases,
        },
      },
    };

the `import` in `main.ts` works fine:  

    import Ipfs from 'ipfs';
    import IpfsHttpClient from 'ipfs-http-client';

But when I add this line:

    const { globSource } = IpfsHttpClient;

I get this error:

    A JavaScript error occurred in the main process
    Uncaught Exception:
    Error: Module build failed (from ./node_modules/@marshallofsound/webpack-asset-relocator-loader/dist/index.js):
    SyntaxError: Unexpected token (85:14)
        at Object.module.exports.pp$4.raise (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules
    /@marshallofsound/webpack-asset-relocator-loader/dist/index.js:20834:13)
        at Object.module.exports.pp.unexpected (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules
    /@marshallofsound/webpack-asset-relocator-loader/dist/index.js:18680:8)
        at Object.module.exports.pp$1.parseTryStatement (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules
    /@marshallofsound/webpack-asset-relocator-loader/dist/index.js:19069:49)
        at Object.module.exports.pp$1.parseStatement (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules
    /@marshallofsound/webpack-asset-relocator-loader/dist/index.js:18834:32)
        at Object.parseStatement (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules/@marshallofsound
    /webpack-asset-relocator-loader/dist/index.js:4539:118)
        at Object.parseStatement (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules/@marshallofsound
    /webpack-asset-relocator-loader/dist/index.js:42314:22)
        at Object.module.exports.pp$1.parseBlock (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules
    /@marshallofsound/webpack-asset-relocator-loader/dist/index.js:19157:23)
        at Object.module.exports.pp$1.parseTryStatement (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules
    /@marshallofsound/webpack-asset-relocator-loader/dist/index.js:19073:24)
        at Object.module.exports.pp$1.parseStatement (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules
    /@marshallofsound/webpack-asset-relocator-loader/dist/index.js:18834:32)
        at Object.parseStatement (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules/@marshallofsound
    /webpack-asset-relocator-loader/dist/index.js:4539:118)
        at Object.parseStatement (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules/@marshallofsound
    /webpack-asset-relocator-loader/dist/index.js:42314:22)
        at Object.module.exports.pp$1.parseBlock (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules
    /@marshallofsound/webpack-asset-relocator-loader/dist/index.js:19157:23)
        at Object.module.exports.pp$3.parseFunctionBody (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules
    /@marshallofsound/webpack-asset-relocator-loader/dist/index.js:20675:22)
        at Object.module.exports.pp$3.parseArrowExpression (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules
    /@marshallofsound/webpack-asset-relocator-loader/dist/index.js:20638:8)
        at Object.module.exports.pp$3.parseExprAtom (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules
    /@marshallofsound/webpack-asset-relocator-loader/dist/index.js:20227:21)
        at Object.parseExprAtom (/home/marco/webMatters/electronMatters/IpfsPlaying/node_modules/@marshallofsound
    /webpack-asset-relocator-loader/dist/index.js:4551:117)
        at Object../node_modules/fs-extra/lib/mkdirs/make-dir.js (/home/marco/webMatters/electronMatters/IpfsPlaying/.webpack
     /main/index.js:13240:7)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/IpfsPlaying/.webpack/main/index.js:21:30)
        at Object../node_modules/fs-extra/lib/mkdirs/index.js (/home/marco/webMatters/electronMatters/IpfsPlaying/.webpack
    /main/index.js:13217:44)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/IpfsPlaying/.webpack/main/index.js:21:30)
        at Object../node_modules/fs-extra/lib/copy-sync/copy-sync.js (/home/marco/webMatters/electronMatters/IpfsPlaying
    /.webpack/main/index.js:12155:20)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/IpfsPlaying/.webpack/main/index.js:21:30)
        at Object../node_modules/fs-extra/lib/copy-sync/index.js (/home/marco/webMatters/electronMatters/IpfsPlaying/.webpack
    /main/index.js:12332:13)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/IpfsPlaying/.webpack/main/index.js:21:30)
        at Object../node_modules/fs-extra/lib/index.js (/home/marco/webMatters/electronMatters/IpfsPlaying/.webpack
    /main/index.js:13083:6)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/IpfsPlaying/.webpack/main/index.js:21:30)
