### ISSUE TITLE
ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by miguelmota** [ipfs/js-ipfs#3558]
- **Version**:
```
"ipfs-core": "^0.5.2"
```

```
node -v
v11.15.0
```

- **Platform**:
```
Linux archlinux 5.10.11-arch1-1 #1 SMP PREEMPT Wed, 27 Jan 2021 13:53:16 +0000 x86_64 GNU/Linux
```

- **Subsystem**:

#### Description:

Error when importing `ipfs-core`

```
/home/mota/Sandbox/ipfs-pubsub/node_modules/native-abort-controller/src/index.js:5
if (globalThis.AbortController && globalThis.AbortSignal) {
^

ReferenceError: globalThis is not defined
    at Object.<anonymous> (/home/mota/Sandbox/ipfs-pubsub/node_modules/native-abort-controller/src/index.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/mota/Sandbox/ipfs-pubsub/node_modules/ipfs-utils/src/http.js:9:29)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)

```
#### Steps to reproduce the error:
```
const IPFS = require('ipfs-core')
```
```
node index.js
```

**Comment by achingbrain** [comment]
Please update to at least Node 12, preferably Node 14 or later

**Comment by miguelmota** [comment]
@achingbrain upgrading node fixed the issue. Thanks!
