### ISSUE TITLE
nodejs error

### ISSUE THREAD

**Issue by Slender1808** [ipfs/js-ipfs#3615]
it is not possible to install ipfs via npm

```
jadson@jadson-linux:~/Área de Trabalho/Effusis/Servidor Arquivos/IPFS/ipfs-nodejs$ npm i ipfs
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/jadson/Área de Trabalho/Effusis/Servidor Arquivos/IPFS/ipfs-nodejs/node_modules/bcrypto
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.16.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.6 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/jadson/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jadson/Área de Trabalho/Effusis/Servidor Arquivos/IPFS/ipfs-nodejs/node_modules/bcrypto/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jadson/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jadson/.cache/node-gyp/14.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/jadson/.cache/node-gyp/14.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/jadson/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/jadson/.cache/node-gyp/14.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/jadson/Área de Trabalho/Effusis/Servidor Arquivos/IPFS/ipfs-nodejs/node_modules/bcrypto',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/home/jadson/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /home/jadson/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/home/jadson/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /home/jadson/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/home/jadson/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /home/jadson/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /home/jadson/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/jadson/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.8.0-49-generic
npm ERR! gyp ERR! command "/home/jadson/.nvm/versions/node/v14.16.0/bin/node" "/home/jadson/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/jadson/Área de Trabalho/Effusis/Servidor Arquivos/IPFS/ipfs-nodejs/node_modules/bcrypto
npm ERR! gyp ERR! node -v v14.16.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jadson/.npm/_logs/2021-04-08T00_33_43_219Z-debug.log
```

**Comment by hugomrdias** [comment]
@Slender1808 you need to install node-gyp toolchain in your system follow these instructions https://github.com/nodejs/node-gyp#installation 

Please reopen if you run into more issues.

**Comment by Slender1808** [comment]
I had installed node-gyp when I tried to install it, I tested different versions of node-gyp and node, but error continues

**Comment by hugomrdias** [comment]
you dont need to install the toolchain for node-gyp ie, `make` and `gcc` 
`npm ERR! gyp ERR! stack Error: not found: make`
