### ISSUE TITLE
jsipfs node with swarm key cannot be connected after some time

### ISSUE THREAD

**Issue by mtiger2k** [ipfs/js-ipfs#3687]
we deployed 2-3 jsipfs nodes in aliyun cloud with swarm key in libp2p config (no bootstrap address configured), and started a local jsipfs node to swarm connect them periodically (also with same swarm key in libp2p config).  But after some time (in the next morning), it failed to swarm connect to those public jsipfs nodes.
we never found such issue with go-ipfs node, but since we want to use js-did to sign data, and couldn't find the solution to add dag-jose format to go-ipfs, we have to use js-ipfs.

Could someone can give some explanation or suggestion?
thx.

**Comment by mtiger2k** [comment]
The following is the error message:
`
Error trying to connect to circuit-relay: 
    Error: stream ended before 1 bytes became available
        at /Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/it-reader/index.js:37:9
        at runMicrotasks (<anonymous>)
        at async /Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/it-length-prefixed/src/decode.js:80:20
        at async oneChunk (/Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/multistream-select/src/multistream.js:12:20)
        at async Object.exports.read (/Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/multistream-select/src/multistream.js:34:15)
        at async module.exports (/Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/multistream-select/src/select.js:21:19)
        at async Upgrader._encryptOutbound (/Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/libp2p/src/upgrader.js:385:36)
        at async Upgrader.upgradeOutbound (/Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/libp2p/src/upgrader.js:167:11)
        at async ClassIsWrapper.dial (/Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/libp2p-tcp/src/index.js:44:18)
    Error: stream ended before 1 bytes became available
        at /Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/it-reader/index.js:37:9
        at runMicrotasks (<anonymous>)
        at async /Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/it-length-prefixed/src/decode.js:80:20
        at async oneChunk (/Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/multistream-select/src/multistream.js:12:20)
        at async Object.exports.read (/Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/multistream-select/src/multistream.js:34:15)
        at async module.exports (/Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/multistream-select/src/select.js:21:19)
        at async Upgrader._encryptOutbound (/Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/libp2p/src/upgrader.js:385:36)
        at async Upgrader.upgradeOutbound (/Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/libp2p/src/upgrader.js:167:11)
        at async ClassIsWrapper.dial (/Users/shaoqintian/ipfs/ipfs-coord-2/node_modules/libp2p-tcp/src/index.js:44:18)
`
