### ISSUE TITLE
Cannot publish to topic

### ISSUE THREAD

**Issue by TheBojda** [ipfs/js-ipfs#3697]
- **Version**:
js-ipfs version: 0.6.1-bdea5bc95073f568a3b0ff75ec5c26a64dd2bee0
interface-ipfs-core version: ^0.145.1
ipfs-http-client version: ^50.0.0
Repo version: 10
System version: x64/linux
Node.js version: v14.17.0
Commit: bdea5bc95073f568a3b0ff75ec5c26a64dd2bee0

- **Platform**:
Linux lacusi-Inspiron-3780 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

#### Severity:
High

#### Description:
Cannot send message to pubsub topic.

I see this in the terminal if debug messages are enabled:
[1621873528422] ERROR (342444 on lacusi-Inspiron-3780): Invalid request query input
    Error: Invalid request query input
        at Object.internals.input (/usr/local/lib/node_modules/ipfs/node_modules/@hapi/hapi/lib/validation.js:148:74)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async Request._lifecycle (/usr/local/lib/node_modules/ipfs/node_modules/@hapi/hapi/lib/request.js:372:32)
        at async Request._execute (/usr/local/lib/node_modules/ipfs/node_modules/@hapi/hapi/lib/request.js:280:9)

#### Steps to reproduce the error:
jsipfs daemon
curl -X POST "http://127.0.0.1:5002/api/v0/pubsub/pub?arg=test&arg=hello"

response:
{"Message":"Invalid request query input","Code":1,"Type":"error"}

**Comment by lidel** [comment]
Please update to the latest jsipfs (js-ipfs-core is 0.11.1 while you are on 0.6) and open a new issue if still happens.
