### ISSUE TITLE
Install of ipfs-core not working

### ISSUE THREAD

**Issue by blmalone** [ipfs/js-ipfs#3777]
- **Version**:
0.9.0

- **Platform**:
MacOS - Node `v13.10.1`

- **Subsystem**:

#### Severity:
Medium

#### Description:
Install not working

#### Steps to reproduce the error:

Running this code produces the following error:
```javascript
const ipfs = require('ipfs-core');

const ipfsStuff  = async () => {
    console.log(ipfs);
}

ipfsStuff();
```

```
ipfs-repo-migrations/migrations/migration-9/pin-set.js:240
      let size = child.Links.reduce((acc, curr) => acc + (curr?.Tsize || 0), 0) + buf.length
                                                               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/blaine.malone/code/moonlander/gems/hardhat/node_modules/ipfs-repo-migrations/migrations/migration-9/index.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
```

**Comment by achingbrain** [comment]
@blmalone from the stack trace it looks like you're running this under node - what version of node are you using?

**Comment by blmalone** [comment]
@achingbrain Node `v13.10.1`

**Comment by achingbrain** [comment]
Please can you upgrade to `v14` or `v16` - these are the supported node versions.

**Comment by blmalone** [comment]
Closing this, it's working now with node `v14.17.4`. 
Thanks.
