### ISSUE TITLE
Resolver already exists for codec "undefined"

### ISSUE THREAD

**Issue by thelamer** [ipfs/js-ipfs#4020]
- **Version**:
"ipfs-http-client": "^55.0.0"

- **Platform**:
5.15.13-200.fc35.x86_64
node v16.13.0

- **Subsystem**:
ipfs-http-client

#### Severity:
Critical - System crash, application panic.

#### Description:
Simply creating the default example panics: 
```
// import ipfs-http-client
const ipfs = require("ipfs-http-client")
// connect to local ipfs node
const client = ipfs.create()
```
Error when run: 
```
Error: Resolver already exists for codec "undefined"
    at Multihashes.addHasher (/home/thelamer/ipfstest/node_modules/ipfs-core-utils/cjs/src/multihashes.js:17:13)
    at new Multihashes (/home/thelamer/ipfstest/node_modules/ipfs-core-utils/cjs/src/multihashes.js:12:12)
    at Object.create (/home/thelamer/ipfstest/node_modules/ipfs-http-client/cjs/src/index.js:104:25)
    at Object.<anonymous> (/home/thelamer/ipfstest/index.js:4:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

I needed to pin back to `51.0.0` to get functional again, I do not believe you introduced this bug, looks like it is from running node @ v16.13.0. 

IE Easy way to duplicate with a head docker container of alpine:
```
docker run --rm -it alpine sh
cd /tmp
npm install  ipfs-http-client
echo 'const ipfs = require("ipfs-http-client")
> const client = ipfs.create()' > index.js
node index.js
```

Alternatively: 
```
docker run --rm -it alpine sh
cd /tmp
npm install ipfs-http-client@51.0.0
echo 'const ipfs = require("ipfs-http-client")
> const client = ipfs.create()' > index.js
node index.js
```

**Comment by rvagg** [comment]
I think https://github.com/multiformats/js-multiformats/pull/163 will deal with this, sorry about that.

**Comment by rvagg** [comment]
@thelamer please try upgrading your dependencies, multiformats@9.6.1 should address this issue
