### ISSUE TITLE
Issue with windows cmd

### ISSUE THREAD

**Issue by D4di69** [ipfs/js-ipfs#4066]
- **Version**:

latest on 15/03/2022 GMT+1 "18:11"
- **Platform**:

windows, cmd
- **Subsystem**:

not known
#### Severity:

Critical

#### Description:

i wanted to try this api with the windows 10 cmd, i opened the cmd as an administrator and typed first "npm install -g ipfs" and npm installed it, i have npm installed and also set to the path. then i typed "jsipfs daemon" to start the daemon but i got this error:
`TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:\Users\sussq\AppData\Roaming\npm\node_modules\ipfs\node_modules\timeout-abort-controller\index.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
`

#### Steps to reproduce the error:

install this with npm on win cmd and then type 'jsipfs daemon'

**Comment by pmuens** [comment]
I'm seeing the exact same error message while following the [OrbitDB Guide](https://github.com/orbitdb/orbit-db/blob/main/GUIDE.md).

Here's a simple code-snippet one can use to reproduce the problem:

```javascript
// NOTE: I'm getting the same error with `ipfs-core` and `ipfs`

// const IPFS = require("ipfs-core");
const IPFS = require("ipfs");
const OrbitDB = require("orbit-db");

async function main() {
  const ipfs1_config = { repo: "./ipfs1" };
  const ipfs1 = await IPFS.create(ipfs1_config);
}

main();
```

Here's the `package.json` file:

```json
{
  "name": "foo",
  "version": "0.1.0",
  "main": "main.js",
  "dependencies": {
    "go-ipfs": "^0.12.0",
    "ipfs": "^0.62.1",
    "ipfs-core": "^0.14.1",
    "ipfsd-ctl": "^10.0.6",
    "orbit-db": "^0.28.3"
  }
}
```

**Comment by BigLep** [comment]
What is the Node version you're using?  Can you please also first try updating to the latest Node version and then report back?

**Comment by D4di69** [comment]
> What is the Node version you're using? Can you please also first try updating to the latest Node version and then report back?

I updated the issue, now you can look what node version im using

**Comment by BigLep** [comment]
2022-03-25 conversation: maintainers will attempt to repo.

**Comment by achingbrain** [comment]
I can't replicate using

Windows 10
node 16.41.2
ipfs 0.62.1

@D4di69 can you please confirm the exact version of node you are using - eg. 16.x.x., not just 16.

**Comment by SgtPooki** [comment]
I was able to get a daemon running by downgrading ipfs:

```
PS C:\Users\Administrator> npm install -g ipfs@0.61
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 6 packages, removed 3 packages, changed 673 packages, and audited 681 packages in 28s

7 vulnerabilities (6 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
PS C:\Users\Administrator> jsipfs daemon
Initializing IPFS daemon...
System version: x64/win32
Node.js version: 16.14.2
Incompatible repo version. Migration needed. Pass --migrate for automatic migration
PS C:\Users\Administrator> jsipfs daemon --migrate
Initializing IPFS daemon...
System version: x64/win32
Node.js version: 16.14.2
The ipfs-repo-migrations package does not have all migration to migrate from version 11 to 12
PS C:\Users\Administrator> rm .jsipfs

Confirm
The item at C:\Users\Administrator\.jsipfs has children and the Recurse parameter was not specified. If you continue,
all children will be removed with the item. Are you sure you want to continue?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
PS C:\Users\Administrator> jsipfs daemon
Initializing IPFS daemon...
System version: x64/win32
Node.js version: 16.14.2
generating Ed25519 keypair...
to get started, enter:

        jsipfs cat /ipfs/QmRaaUwTNfwgFZpeUy8qrZwrp2dY4kCKmmB5xEqvH3vtD1/readme

Swarm listening on /ip4/172.20.224.1/tcp/4002/p2p/12D3KooWMV5SKK2rraFNgtPtY3yzrEtEBKfdHeLETEeQzQx8UzpY
Swarm listening on /ip4/192.168.3.51/tcp/4002/p2p/12D3KooWMV5SKK2rraFNgtPtY3yzrEtEBKfdHeLETEeQzQx8UzpY
Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/12D3KooWMV5SKK2rraFNgtPtY3yzrEtEBKfdHeLETEeQzQx8UzpY
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/12D3KooWMV5SKK2rraFNgtPtY3yzrEtEBKfdHeLETEeQzQx8UzpY
js-ipfs version: 0.13.0
HTTP API listening on /ip4/127.0.0.1/tcp/5002/http
gRPC listening on /ip4/127.0.0.1/tcp/5003/ws
Gateway (read only) listening on /ip4/127.0.0.1/tcp/9090/http
Web UI available at http://127.0.0.1:5002/webui
Daemon is ready
```

**Comment by wandyyd** [comment]
Hi, I can confirm this also happened on fresh installation (I'm not Linux / Tech savvy, so pardon if I did something wrong)

I'm on linux Ubuntu 18.04.6 LTS

Here's the details
<pre>
~$ npm -g ls
/path/to/home/ipfs/.nvm/versions/node/v16.14.2/lib
+-- corepack@0.10.0
+-- ipfs@0.62.1
`-- npm@8.5.5
</pre>

When doing `jsipfs daemon` it gives

<pre>
jsipfs daemon
Initializing IPFS daemon...
System version: x64/linux
Node.js version: 16.14.2
generating Ed25519 keypair...
PubsubRouter is not a constructor
~$ jsipfs add ./test-1.png
PubsubRouter is not a constructor
</pre>

But, when, downgrade to ipfs@0.61.0, it works well as @SgtPooki mentioned.

**Comment by achingbrain** [comment]
It looks like `libp2p-gossipsub@0.13.2` caused this issue, it doesn't exist with `0.13.0` - https://github.com/ChainSafe/js-libp2p-gossipsub/issues/224

**Comment by resession** [comment]
getting this exact same error

**Comment by achingbrain** [comment]
@resession can you confirm the version of `libp2p-gossipsub` you are using?

Run this in your project/where npm has installed js-ipfs:

```console
npm ls libp2p-gossipsub
```

E.g. I use nvm to manage node installs, so I do:

```console
% cd $NVM_DIR/versions/node/`node -v`/lib/node_modules/ipfs
% npm ls libp2p-gossipsub
ipfs@0.62.2 /Users/alex/.nvm/versions/node/v16.13.0/lib/node_modules/ipfs
└─┬ ipfs-core@0.14.2
  └─┬ ipfs-core-config@0.3.2
    └── libp2p-gossipsub@0.13.0
```

**Comment by resession** [comment]
> @resession can you confirm the version of `libp2p-gossipsub` you are using?
> 
> Run this in your project/where npm has installed js-ipfs:
> 
> ```
> npm ls libp2p-gossipsub
> ```
> 
> E.g. I use nvm to manage node installs, so I do:
> 
> ```
> % cd $NVM_DIR/versions/node/`node -v`/lib/node_modules/ipfs
> % npm ls libp2p-gossipsub
> ipfs@0.62.2 /Users/alex/.nvm/versions/node/v16.13.0/lib/node_modules/ipfs
> └─┬ ipfs-core@0.14.2
>   └─┬ ipfs-core-config@0.3.2
>     └── libp2p-gossipsub@0.13.0
> ```

i downgraded the ipfs version, i'll install the latest version again and post the results here tomorrow

**Comment by resession** [comment]
@achingbrain 

i ran that command, here is what i get

`project-test@1.0.0-68 F:\Proj\Production\project-test
└─┬ ipfs@0.62.2
  └─┬ ipfs-core@0.14.2
    └─┬ ipfs-core-config@0.3.2
      └── libp2p-gossipsub@0.13.0`

**Comment by achingbrain** [comment]
Hmm, weird - that should work.  Can you please create a small repro repo and link to it here?  Just an `index.js` that starts a js-ipfs node, a `package.json` and a `package-lock.json` should be enough.

**Comment by wandyyd** [comment]
@achingbrain - thanks for that!
I already test on my own and it works so far. At least new update solve the problem I mentioned previously (below)

<details>
<summary>Previous related issue</summary>
> Hi, I can confirm this also happened on fresh installation (I'm not Linux / Tech savvy, so pardon if I did something wrong)
> 
> I'm on linux Ubuntu 18.04.6 LTS
> 
> Here's the details
> 
> ~$ npm -g ls
> /path/to/home/ipfs/.nvm/versions/node/v16.14.2/lib
> +-- corepack@0.10.0
> +-- ipfs@0.62.1
> `-- npm@8.5.5
> 
> When doing `jsipfs daemon` it gives
> 
> jsipfs daemon
> Initializing IPFS daemon...
> System version: x64/linux
> Node.js version: 16.14.2
> generating Ed25519 keypair...
> PubsubRouter is not a constructor
> ~$ jsipfs add ./test-1.png
> PubsubRouter is not a constructor
> 
> But, when, downgrade to ipfs@0.61.0, it works well as @SgtPooki mentioned.
</details>

**Comment by hjkl451203** [comment]
`npm install --save abortcontroller-polyfill`


`const { AbortController } = globalThis`
換成
```
const { AbortController, abortableFetch } = require('abortcontroller-polyfill/dist/cjs-ponyfill');
const { fetch } = abortableFetch(require('node-fetch'));
```
可正常運作

**Comment by achingbrain** [comment]
Closing as this appears to have been resolved in the latest version.
