### ISSUE TITLE
"process is not defined" error when using IPFS + React

### ISSUE THREAD

**Issue by AlexMesser** [ipfs/js-ipfs#4094]
- **Version**: 0.14.3

- **Platform**: macOS Monterey, Google Chrome 101.0.4951.54 

- **Subsystem**:

#### Description:

I am using [browser-create-react-app](https://github.com/ipfs-examples/js-ipfs-examples/tree/master/examples/browser-create-react-app) example. I just tried to add a custom swarm addresses to IPFS node:

```js
ipfs = await create({
   config: {
   Addresses: {
      Swarm: [
          // This is a public webrtc-star server
         '/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star',
         '/dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star',
      ],
   },
  }
})
```

And I got the error in console:

```
Uncaught ReferenceError: process is not defined
    at maybeReadMore (_stream_readable.js:561:1)
    at addChunk (_stream_readable.js:306:1)
    at readableAddChunk (_stream_readable.js:280:1)
    at Peer.Readable.push (_stream_readable.js:241:1)
    at Peer._onChannelMessage (index.js:915:1)
    at RTCDataChannel._channel.onmessage (index.js:465:1)
```

![Screen Shot 2022-05-12 at 18 10 46](https://user-images.githubusercontent.com/17142628/168093573-ffe42dcc-9035-4aa9-9222-1c725814ada7.png)

Also, when I am trying to establish direct swarm connection I am getting the similar error:

```js
await ipfs.swarm.connect(<multiaddr>)
```

error:

```
index.js:31 Uncaught (in promise) AggregateError: 
    ReferenceError: process is not defined
        at Peer.Readable.on (http://localhost:3000/static/js/bundle.js:148762:9)
        at createReadableStreamAsyncIterator (http://localhost:3000/static/js/bundle.js:150206:10)
        at Peer.Readable.<computed> (http://localhost:3000/static/js/bundle.js:148950:12)
        at getIterator (http://localhost:3000/static/js/bundle.js:22639:39)
        at toMultiAbortableSource (http://localhost:3000/static/js/bundle.js:10586:12)
        at toAbortableSource (http://localhost:3000/static/js/bundle.js:10580:56)
        at module.exports (http://localhost:3000/static/js/bundle.js:63070:30)
        at ClassIsWrapper.dial (http://localhost:3000/static/js/bundle.js:62590:20)
        at async TransportManager.dial (http://localhost:3000/static/js/bundle.js:76443:14)
        at async http://localhost:3000/static/js/bundle.js:67552:18
    ReferenceError: process is not defined
        at Peer.Readable.on (http://localhost:3000/static/js/bundle.js:148762:9)
        at createReadableStreamAsyncIterator (http://localhost:3000/static/js/bundle.js:150206:10)
        at Peer.Readable.<computed> (http://localhost:3000/static/js/bundle.js:148950:12)
        at getIterator (http://localhost:3000/static/js/bundle.js:22639:39)
        at toMultiAbortableSource (http://localhost:3000/static/js/bundle.js:10586:12)
        at toAbortableSource (http://localhost:3000/static/js/bundle.js:10580:56)
        at module.exports (http://localhost:3000/static/js/bundle.js:63070:30)
        at ClassIsWrapper.dial (http://localhost:3000/static/js/bundle.js:62590:20)
        at async TransportManager.dial (http://localhost:3000/static/js/bundle.js:76443:14)
        at async http://localhost:3000/static/js/bundle.js:67552:18
    at maybeSettle (http://localhost:3000/static/js/bundle.js:105393:14)
    at http://localhost:3000/static/js/bundle.js:105431:27
```

**Comment by AlexMesser** [comment]
**UPD:** can't reproduce it on version `0.15.2`

**Comment by achingbrain** [comment]
This sounds like it's been resolved so I am going to close this issue.
