### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by jitendrapal080791** [ipfs/js-ipfs#4110]
FAIL  src/App.test.js
  ● Test suite failed to run

    TypeError: Class extends value undefined is not a constructor or null

       5 | import { getUserForUpdateDb } from "../db/mongodb";
       6 | import { toast } from "react-toastify";
    >  7 | import { create } from "ipfs-http-client";
         | ^
       8 |
       9 | const EditProfile = ({ contractX, account, wallet }) => {
      10 |     const client = create("https://ipfs.infura.io:5001/api/v0");

      at Object.<anonymous> (node_modules/@ipld/dag-json/cjs/index.js:79:53)
      at Object.<anonymous> (node_modules/ipfs-http-client/cjs/src/index.js:10:15)
      at Object.<anonymous> (src/components/editprofile.js:7:1)
      at Object.<anonymous> (src/App.js:7:1)
      at Object.<anonymous> (src/App.test.js:3:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.028 s
Ran all test suites.

I am getting above error when run command `npm run test` in react project.

**Comment by Dnouv** [comment]
Hello,
First of all, thank you for your hard work, the project is futuristic and phenomenal.
I have also encountered a similar error while trying to run `npm run build` in a NextJS project. It returned 
```
> Build error occurred
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (...node_modules/timeout-abort-controller/index.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24) {
  type: 'TypeError'
}
```
The versions-
Node: v14.18.3
npm: v6.14.15
Environment: WSL.

Any help would be really appreciated. Thank you!

**Comment by BigLep** [comment]
Unfortunately we can't support node 14.  You'll need to use a polyfill or upgrade node.

https://github.com/ipfs/community/blob/master/CONTRIBUTING_JS.md#supported-versions
