### ISSUE TITLE
js-ipfs.files.read(CID) on linux does not read data stored in windows

### ISSUE THREAD

**Issue by resession** [ipfs/js-ipfs#4140]
**Version**: 0.63.3

**Platform**: Linux name 5.4.0-120-generic #136-Ubuntu SMP Fri Jun 10 13:40:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Subsystem**: MFS

Severity: High

Description: When i use `js-ipfs.files.read(CID)` on my linux computer to read a file that is being stored on my windows computer, it throws an error
What you did - try to use `js-ipfs.files.read(CID)` on my windows computer to pull data from my linux computer, it worked, so it is a linux/js-ipfs issue
What happened - when i use `js-ipfs.files.read(CID)` on my linux computer to read data that is stored on my windows computer, it throws an error
What you expected to happen - when i use `js-ipfs.files.read(CID)` on my linux computer, it should return the file data that is stored on my windows computer

Steps to reproduce the error: write data on a windows computer(you can use `js-ipfs.files.write(somePath, someData))`, then use the windowsCID you get from that and use it on a linux computer using `js-ipfs.files.read(windowsCID)`, doing this i get the following error. if i do this same thing on windows to read data that is stored on my linux computer, then it works, but not vice-versa.

```TimeoutError: request timed out at maybeThrowTimeoutError(file:///home/name/Proj/hybrid-browser/node_modules/ipfs-core-utils/src/with-timeout-option.js:41:15) at file:///home/name/Proj/hybrid-browser/node_modules/ipfs-core-utils/src/with-timeout-option.js:97:9 at runNextTicks (node:internal/process/task_queues:61:5) at process.processTimers (node:internal/timers:499:9) at async file:///home/name/Proj/hybrid-browser/node_modules/ipfs-core/src/components/files/utils/create-lock.js:33:18 at async /home/name/Proj/hybrid-browser/node_modules/chunk-fetch/index.js:211:22 at async fetch (/home/name/Proj/hybrid-browser/node_modules/make-fetch/index.js:35:9) at async AsyncFunction.protocolHandler (/home/name/Proj/hybrid-browser/app/protocols/fetch-to-handler.js:49:24)```

**Comment by resession** [comment]
this can be closed. data is now loading fine on linux from windows. it takes a long time, but it still loads. closing this.
