### ISSUE TITLE
[Again] MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to 

### ISSUE THREAD

**Issue by chiro-hiro** [ipfs/js-ipfs#4321]
**Version**:
{
  version: '0.18.0',
  commit: '',
  repo: '12',
  'ipfs-core': '0.18.0',
  'interface-ipfs-core': '^0.158.0'
}

Node.js v16.18.1

- **Platform**:
Darwin Chiros-MacBook-Pro.local 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:49:43 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T8103 arm64

- **Subsystem**:
DAG

#### Severity:

Medium

#### Description:
I use, `ipfs.dag.get()` and `ipfs.dag.put()` to update my DAG. Got this error whenever I leave it run for around 1 min.

```txt
(node:11250) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
    at AbortSignal.[kNewListener] (node:internal/event_target:519:17)
    at AbortSignal.[kNewListener] (node:internal/abort_controller:180:24)
    at AbortSignal.addEventListener (node:internal/event_target:628:23)
    at abortable (file:///Users/chiro/GitHub/zkDatabase/zkdb/node_modules/abortable-iterator/dist/src/index.js:13:16)
    at abortable.next (<anonymous>)
    at file:///Users/chiro/GitHub/zkDatabase/zkdb/node_modules/it-handshake/dist/src/index.js:14:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async abortable (file:///Users/chiro/GitHub/zkDatabase/zkdb/node_modules/abortable-iterator/dist/src/index.js:28:26)
    at async Object.sink (file:///Users/chiro/GitHub/zkDatabase/zkdb/node_modules/@libp2p/mplex/dist/src/stream.js:127:32)
```

#### Steps to reproduce the error:
```ts

  public async put<T>(collection: string, document: T, option?: PutOptions) {
    await this.loadCollection(collection);
    let documentDigest = await this.poseidonHash(document);

    const result = await this.nodeInstance.dag.put(document, {
      pin: true,
      ...option,
    });
    const cid = result.toString();
    this.collections[collection][documentDigest] = cid;

    await this.nodeInstance.files.write(
      this.getCollectionPath(collection),
      JSON.stringify(this.collections[collection])
    );

    return {
      CID: cid,
      documentID: documentDigest,
      timestamp: Date.now(),
      database: this.config.database,
      collection,
      document,
    };
  }
```

**Comment by achingbrain** [comment]
js-IPFS is in the process of being deprecated, the replacement is [Helia](https://github.com/ipfs/helia) - please see the [State of IPFS in JS](https://blog.ipfs.tech/state-of-ipfs-in-js/) post for a bit of background and the [migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS) for how to port your app over.

Please can you try with Helia, all of these warnings should have been squished in the latest libp2p releases - please open an issue if not.
