### ISSUE TITLE
[Linux] jsipfs tool throws error: Error: Cannot find module 'lodash.isfunction'

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/js-ipfs#526]
This is a clean install from npm:

```
hector@thinkpad ~> sudo npm install ipfs --global
npm WARN deprecated lodash.contains@2.4.3: This package is discontinued. Use lodash.includes@^4.0.0.
npm WARN deprecated pull@2.1.1: unmaintained
/usr/bin/jsipfs -> /usr/lib/node_modules/ipfs/src/cli/bin.js
npm WARN unmet dependency /usr/lib/node_modules/ipfs/node_modules/hapi/node_modules/subtext/node_modules/pez requires boom@'3.x.x' but will load
npm WARN unmet dependency /usr/lib/node_modules/ipfs/node_modules/hapi/node_modules/boom,
npm WARN unmet dependency which is version 4.0.0
ipfs@0.17.0 /usr/lib/node_modules/ipfs
├── detect-node@2.0.3
├── path-exists@3.0.0
├── lodash.values@4.3.0
├── lodash.set@4.3.2
├── lodash.get@4.4.2
├── lodash.has@4.5.2
├── lodash.flatmap@4.5.0
├── lodash.sortby@4.7.0
├── pull-sort@1.0.0
├── promisify-es6@1.0.2
├── pull-zip@2.0.0
├── pull-paramap@1.2.0
├── isstream@0.1.2
├── pull-pushable@2.0.1
├── run-waterfall@1.1.3
├── run-parallel-limit@1.0.3
├── run-parallel@1.1.6
├── run-series@1.1.4
├── pull-stream-to-stream@1.3.3
├── mafmt@2.1.2
├── multihashes@0.2.2
├── boom@4.2.0 (hoek@4.1.0)
├── peer-book@0.3.0
├── bs58@3.0.0 (base-x@1.0.4)
├── ipfs-block-service@0.5.0
├── debug@2.2.0 (ms@0.7.1)
├── stream-to-pull-stream@1.7.2 (looper@3.0.0)
├── temp@0.8.3 (os-tmpdir@1.0.2, rimraf@2.2.8)
├── map-limit@0.0.1 (once@1.3.3)
├── pull-file@1.0.0 (pull-utf8-decoder@1.0.2)
├── through2@2.0.1 (xtend@4.0.1, readable-stream@2.0.6)
├── bl@1.1.2 (readable-stream@2.0.6)
├── glob@7.1.1 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0, minimatch@3.0.3)
├── multiaddr@2.0.3 (lodash.map@4.6.0, lodash.filter@4.6.0, varint@4.0.1, ip@1.1.3, xtend@4.0.1)
├── fs-pull-blob-store@0.3.0 (pull-write-file@0.2.1, pull-defer@0.2.2, pull-file@0.5.0, mkdirp@0.5.1)
├── yargs@6.2.0 (get-caller-file@1.0.2, decamelize@1.2.0, camelcase@3.0.0, y18n@3.2.1, which-module@1.0.0, set-blocking@2.0.0, window-size@0.2.0, yargs-parser@4.0.2, require-main-filename@1.0.1, require-directory@2.1.1, string-width@1.0.2, cliui@3.2.0, os-locale@1.4.0)
├── pull-stream@3.4.5
├── peer-info@0.7.1
├── ipfs-repo@0.9.1 (pull-write@1.1.0, safe-buffer@5.0.1, lock@0.1.3, pull-defer@0.2.2, base32.js@0.1.0)
├── update-notifier@1.0.2 (is-npm@1.0.0, lazy-req@1.1.0, xdg-basedir@2.0.0, semver-diff@2.1.0, chalk@1.1.3, boxen@0.6.0, configstore@2.1.0, latest-version@2.0.0)
├── read-pkg-up@1.0.1 (find-up@1.1.2, read-pkg@1.1.0)
├── idb-pull-blob-store@0.4.0 (pull-write@1.1.0, pull-defer@0.2.2, typedarray-to-buffer@3.1.2, pull-window@2.1.4, dexie@1.5.0)
├── ipfs-unixfs-engine@0.11.4 (pull-write@1.1.0, pull-traverse@1.0.3, is-ipfs@0.2.1, pull-block@1.0.2)
├── ipfs-multipart@0.1.0 (content@3.0.2, dicer@0.2.5)
├── ipfs-api@9.0.0 (flatmap@0.0.3, streamifier@0.1.1, qs@6.3.0, wreck@10.0.0, multipart-stream@2.0.1, is-ipfs@0.2.1, tar-stream@1.5.2, ndjson@1.4.3)
├── ipfs-block@0.3.0 (multihashing@0.2.1)
├── ipfs-unixfs@0.1.4 (protocol-buffers@3.1.6)
├── ipfs-merkle-dag@0.7.3 (stable@0.1.5, pull-traverse@1.0.3, is-ipfs@0.2.1, multihashing@0.2.1, protocol-buffers@3.1.6)
├── ipfs-bitswap@0.7.1 (lodash.isundefined@3.0.1, lodash.isequalwith@4.4.0, pull-generate@2.2.0, heap@0.2.6, pull-defer@0.2.2, pull-length-prefixed@1.2.0, protocol-buffers@3.1.6)
├── joi@9.2.0 (topo@2.0.2, items@2.1.1, isemail@2.2.1, hoek@4.1.0, moment@2.15.1)
├── hapi@15.1.1 (catbox-memory@2.0.3, topo@2.0.2, boom@4.0.0, items@2.1.1, podium@1.2.3, hoek@4.0.2, shot@3.3.2, ammo@2.0.2, iron@4.0.3, statehood@5.0.0, heavy@4.0.2, cryptiles@3.0.2, catbox@7.1.2, call@3.0.3, accept@2.1.2, mimos@3.0.3, subtext@4.2.2, joi@9.0.4)
├── libp2p-ipfs@0.14.1 (libp2p-websockets@0.8.1, libp2p-tcp@0.8.1, libp2p-spdy@0.9.0, libp2p-secio@0.5.0, libp2p-swarm@0.23.0)
├── peer-id@0.7.0 (libp2p-crypto@0.5.0)
├── libp2p-ipfs-browser@0.15.1 (libp2p-websockets@0.8.1, libp2p-webrtc-star@0.4.5, libp2p-spdy@0.9.0, libp2p-secio@0.5.0, libp2p-swarm@0.23.0)
├── async@2.1.2 (lodash@4.16.4)
└── babel-runtime@6.11.6 (regenerator-runtime@0.9.5, core-js@2.4.1)
hector@thinkpad ~> jsipfs 
module.js:327
    throw err;
    ^

Error: Cannot find module 'lodash.isfunction'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/ipfs/node_modules/libp2p-ipfs/node_modules/libp2p-tcp/lib/index.js:11:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by VictorBjelkholm** [comment]
Could you share the output of running `npm version`?

**Comment by hsanjuan** [comment]
My bad. npm package version != npm version in OpenSUSE. Works now. Thanks.

**Comment by redcherry999** [comment]
**Hello sir ,

i'm getting same errror as**

`module.js:327
throw err;
^

Error: Cannot find module 'readable-stream'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/home/root/aws_nodejs/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/store.js:2:16)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
`
**i have run the command "npm i npm -g" to get npm 3 but it is giving same error
i have npm 4.3.0 version
could you please help me**
