### ISSUE TITLE
Non-base58 character when trying to do `jsipfs files cat`

### ISSUE THREAD

**Issue by phil-r** [ipfs/js-ipfs#535]
Hi! 
I've decided to try out the project and ran the following code:

``` bash
jsipfs init
```

That generated the following output:

```
initializing ipfs node at /Users/phil/.ipfs
generating 2048-bit RSA keypair...done
peer identity: QmeLtmb2QUkm5DAVZKANV7YydAFBP6ATiZATD1UzvhAwYE
to get started, enter:

     jsipfs files cat /ipfs/QmegvLXxpVKiZ4b57Xs1syfBVRd8CbucVHAp7KpLQdGieC/readme
```

After that I tried to run

``` bash
jsipfs files cat /ipfs/QmegvLXxpVKiZ4b57Xs1syfBVRd8CbucVHAp7KpLQdGieC/readme
```

and got the following error:

```
/usr/local/lib/node_modules/ipfs/node_modules/base-x/index.js:57
      if (value === undefined) throw new Error('Non-base' + BASE + ' character')
                               ^

Error: Non-base58 character
    at Object.decode (/usr/local/lib/node_modules/ipfs/node_modules/base-x/index.js:57:38)
    at Object.fromB58String (/usr/local/lib/node_modules/ipfs/node_modules/multihashes/lib/index.js:33:26)
    at normalizeKey (/usr/local/lib/node_modules/ipfs/node_modules/ipfs-merkle-dag/lib/dag-service.js:123:15)
    at DAGService.getStream (/usr/local/lib/node_modules/ipfs/node_modules/ipfs-merkle-dag/lib/dag-service.js:56:27)
    at DAGService.get (/usr/local/lib/node_modules/ipfs/node_modules/ipfs-merkle-dag/lib/dag-service.js:48:17)
    at Function.cat.promisify (/usr/local/lib/node_modules/ipfs/src/core/components/files.js:55:18)
    at Object.cat (/usr/local/lib/node_modules/ipfs/node_modules/promisify-es6/index.js:34:27)
    at waterfall (/usr/local/lib/node_modules/ipfs/src/cli/commands/files/cat.js:21:32)
    at nextTask (/usr/local/lib/node_modules/ipfs/node_modules/async/waterfall.js:28:14)
    at /usr/local/lib/node_modules/ipfs/node_modules/async/waterfall.js:22:13
```

Am I doing something wrong?

**Comment by phil-r** [comment]
Running 
`ipfs cat /ipfs/QmegvLXxpVKiZ4b57Xs1syfBVRd8CbucVHAp7KpLQdGieC/readme` 
gives
`Error: ipfs repo needs migration.`

**Comment by VictorBjelkholm** [comment]
Hey, the initial problem you mention is because we don't handle subfiles yet (the hash/file part), there is an open issue here: https://github.com/ipfs/js-ipfs/issues/478

The second problem you mention seems to be that you're trying to use the js-ipfs repo from go-ipfs which I don't think is supported atm, @diasdavid probably knows more.

**Comment by diasdavid** [comment]
It should definitely work, which go-ipfs version are you using?

**Comment by dignifiedquire** [comment]
@diasdavid I'm not sure we bumped the repo version the last time go bumped it

**Comment by phil-r** [comment]
@VictorBjelkholm 
> you're trying to use the js-ipfs repo from go-ipfs 
Yep that's exactly what I was trying to do after `js-ipfs` wasn't working

@diasdavid I'll check versions when I'll be on my home computer.

**Comment by chovy** [comment]
not fixed. still seeing it. ipfs/js-ipfs/issues/589
