### ISSUE TITLE
example fails (mac/node-6)

### ISSUE THREAD

**Issue by chovy** [ipfs/js-ipfs#589]
Did the install `npm i -g ipfs` under node v.6.6.0

	$ jsipfs init
	initializing ipfs node at /Users/user/.ipfs
	generating 2048-bit RSA keypair...done
	peer identity: QmaQfvcKmjpUpYUwWCESp81oV3ussMatpVDHp3ydgWnbjT
	to get started, enter:

		 jsipfs files cat /ipfs/QmegvLXxpVKiZ4b57Xs1syfBVRd8CbucVHAp7KpLQdGieC/readme

	$ jsipfs files cat /ipfs/QmegvLXxpVKiZ4b57Xs1syfBVRd8CbucVHAp7KpLQdGieC/readme
	/Users/user/.nvm/versions/node/v6.6.0/lib/node_modules/ipfs/node_modules/base-x/index.js:57
	      if (value === undefined) throw new Error('Non-base' + BASE + ' character')
	                               ^

	Error: Non-base58 character
	    at Object.decode (/Users/user/.nvm/versions/node/v6.6.0/lib/node_modules/ipfs/node_modules/base-x/index.js:57:38)
	    at Object.fromB58String (/Users/user/.nvm/versions/node/v6.6.0/lib/node_modules/ipfs/node_modules/multihashes/lib/index.js:33:26)
	    at new CID (/Users/user/.nvm/versions/node/v6.6.0/lib/node_modules/ipfs/node_modules/cids/lib/index.js:41:29)
	    at Function.cat.promisify (/Users/user/.nvm/versions/node/v6.6.0/lib/node_modules/ipfs/src/core/components/files.js:57:30)
	    at Object.cat (/Users/user/.nvm/versions/node/v6.6.0/lib/node_modules/ipfs/node_modules/promisify-es6/index.js:34:27)
	    at waterfall (/Users/user/.nvm/versions/node/v6.6.0/lib/node_modules/ipfs/src/cli/commands/files/cat.js:21:32)
	    at nextTask (/Users/user/.nvm/versions/node/v6.6.0/lib/node_modules/ipfs/node_modules/async/waterfall.js:28:14)
	    at /Users/user/.nvm/versions/node/v6.6.0/lib/node_modules/ipfs/node_modules/async/waterfall.js:22:13
	    at apply (/Users/user/.nvm/versions/node/v6.6.0/lib/node_modules/ipfs/node_modules/lodash/_apply.js:15:25)
	    at /Users/user/.nvm/versions/node/v6.6.0/lib/node_modules/ipfs/node_modules/lodash/_overRest.js:32:12

**Comment by diasdavid** [comment]
Sorry about that hurdle, unfortunately, the unixfs-engine impl in JS does not support path notation yet, follow https://github.com/ipfs/js-ipfs/issues/478 for further developments.
