### ISSUE TITLE
errors during jsipfs init

### ISSUE THREAD

**Issue by chriswingler** [ipfs/js-ipfs#629]
Hi, I'm getting this error when running `jsipfs init`

`chris@chris-MS-7882:~/workspace$ jsipfs init
initializing ipfs node at /home/chris/.ipfs
(node:3964) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
generating 2048-bit RSA keypair...done
peer identity: QmVaNQjTTeg4TjUT2fwXbEbCC7tb7ELukaBDxfqYUVTdD1
undefined:5
  if (!defined(obj.Type)) throw new Error("Type is required")
                          ^

Error: Type is required
    at encodingLength (eval at line.toFunction (/usr/local/lib/node_modules/ipfs/node_modules/generate-function/index.js:55:21), <anonymous>:5:33)
    at Object.encode (eval at line.toFunction (/usr/local/lib/node_modules/ipfs/node_modules/generate-function/index.js:55:21), <anonymous>:5:30)
    at Data.marshal (/usr/local/lib/node_modules/ipfs/node_modules/ipfs-unixfs/src/index.js:68:23)
    at pull.asyncMap (/usr/local/lib/node_modules/ipfs/node_modules/ipfs-unixfs-engine/src/importer/index.js:123:24)
    at /usr/local/lib/node_modules/ipfs/node_modules/pull-stream/throughs/async-map.js:28:13
    at pull (/usr/local/lib/node_modules/ipfs/node_modules/pull-through/index.js:46:22)
    at next (/usr/local/lib/node_modules/ipfs/node_modules/pull-through/node_modules/looper/index.js:7:11)
    at /usr/local/lib/node_modules/ipfs/node_modules/pull-through/node_modules/looper/index.js:9:18
    at /usr/local/lib/node_modules/ipfs/node_modules/pull-through/index.js:62:13
    at /usr/local/lib/node_modules/ipfs/node_modules/pull-file/index.js:137:9`

**Comment by diasdavid** [comment]
Sorry about that @chriswingler, it was a regression that happened in one of our dependencies -- `protocol-buffers` --, https://github.com/ipfs/js-ipfs/pull/625#issuecomment-263006537

I just fixed "the regression regression" and it should be all good :) Let me know if you find any other issue.
