### ISSUE TITLE
Error while initializing jsipfs

### ISSUE THREAD

**Issue by iamdebu** [ipfs/js-ipfs#695]
# I got the below error while running jsipfs init (in Ubuntu 14.05)

initializing ipfs node at /home/gtoadmin/.jsipfs
generating 2048-bit RSA keypair.../home/gtoadmin/.nvm/versions/node/v5.0.0/lib/node_modules/ipfs/node_modules/libp2p-crypto/src/crypto/util.js:18
  return new BN(Buffer.from(str, 'base64'))
                       ^

TypeError: base64 is not a function
    at Function.from (native)
    at Function.from (native)
    at toBn (/home/gtoadmin/.nvm/versions/node/v5.0.0/lib/node_modules/ipfs/node_modules/libp2p-crypto/src/crypto/util.js:18:24)
    at Object.exports.jwkToPkix (/home/gtoadmin/.nvm/versions/node/v5.0.0/lib/node_modules/ipfs/node_modules/libp2p-crypto/src/crypto/rsa-utils.js:109:18)
    at RsaPublicKey.marshal (/home/gtoadmin/.nvm/versions/node/v5.0.0/lib/node_modules/ipfs/node_modules/libp2p-crypto/src/keys/rsa.js:20:25)
    at RsaPublicKey.bytes (/home/gtoadmin/.nvm/versions/node/v5.0.0/lib/node_modules/ipfs/node_modules/libp2p-crypto/src/keys/rsa.js:26:18)
    at RsaPublicKey.hash (/home/gtoadmin/.nvm/versions/node/v5.0.0/lib/node_modules/ipfs/node_modules/libp2p-crypto/src/keys/rsa.js:40:22)
    at /home/gtoadmin/.nvm/versions/node/v5.0.0/lib/node_modules/ipfs/node_modules/peer-id/src/index.js:107:37
    at nextTask (/home/gtoadmin/.nvm/versions/node/v5.0.0/lib/node_modules/ipfs/node_modules/async/waterfall.js:28:14)
    at /home/gtoadmin/.nvm/versions/node/v5.0.0/lib/node_modules/ipfs/node_modules/async/waterfall.js:22:13

**Comment by diasdavid** [comment]
This was fixed with the latest libp2p-crypto release that got released with js-ipfs 0.21.0.

Try it again, shouldn't be a problem anymore, if there is, let us know :)

Also, try one of the LTS node.js version (4 or 6), Node.js 5 is not supported anymore.
