### ISSUE TITLE
Issue Running Tests Or Build

### ISSUE THREAD

**Issue by svozza** [ipfs/js-ipfs#700]
Apologies if this is a noob mistake but after cloning the repo I can't seem to run the tests or the build, i.e., folloing the steps [here](https://github.com/ipfs/js-ipfs#development). First there is an error when doing `npm install`:

```
> node-webcrypto-ossl@1.0.16 build:es5 /home/stefano/git/js-ipfs/node_modules/libp2p-ipfs-browser/node_modules/libp2p/node_modules/libp2p-ping/node_modules/libp2p-crypto/node_modules/node-webcrypto-ossl
> tsc

sh: 1: tsc: not found

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/home/stefano/.nvm/versions/node/v4.4.5/bin/node" "/home/stefano/.nvm/versions/node/v4.4.5/bin/npm" "run" "build:es5"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! node-webcrypto-ossl@1.0.16 build:es5: `tsc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-webcrypto-ossl@1.0.16 build:es5 script 'tsc'.
npm ERR! This is most likely a problem with the node-webcrypto-ossl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-webcrypto-ossl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-webcrypto-ossl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/stefano/git/js-ipfs/node_modules/libp2p-ipfs-browser/node_modules/libp2p/node_modules/libp2p-ping/node_modules/libp2p-crypto/node_modules/node-webcrypto-ossl/npm-debug.log

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/home/stefano/.nvm/versions/node/v4.4.5/bin/node" "/home/stefano/.nvm/versions/node/v4.4.5/bin/npm" "run" "build"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! node-webcrypto-ossl@1.0.16 build: `npm run build:es5`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-webcrypto-ossl@1.0.16 build script 'npm run build:es5'.
npm ERR! This is most likely a problem with the node-webcrypto-ossl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:es5
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-webcrypto-ossl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-webcrypto-ossl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/stefano/git/js-ipfs/node_modules/libp2p-ipfs-browser/node_modules/libp2p/node_modules/libp2p-ping/node_modules/libp2p-crypto/node_modules/node-webcrypto-ossl/npm-debug.log
```

And the if I do `npm test` I get this:

```
> ipfs@0.20.4 test /home/stefano/git/js-ipfs
> gulp test

module.js:327
    throw err;
    ^

Error: Cannot find module 'bs58'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/stefano/git/js-ipfs/node_modules/ipld-resolver/node_modules/ipld-dag-pb/src/resolver.js:4:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
npm ERR! Test failed.  See above for more details.
```

I'm riunning Node v4.4.5 but I still have similar problems with Node 6.9.1.

**Comment by VictorBjelkholm** [comment]
Seems you're running npm@2 and we have a requirement on using npm@3 or
higher.

**Comment by svozza** [comment]
Aha. The reason why Node 6 didn't work for me was because I hadn't done an `rm -rf node_modules`. Thanks for the quick response!
