### ISSUE TITLE
Failing tests on ubuntu+osx on current master

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js-ipfs#766]
While trying to get the jenkins integration to work, I've noticed that there is some tests failing on both ubuntu and osx when running the browser+node tests. cc @diasdavid 

Failing tests:

### browser
```
  1) bitswap connections fetches a remote block 2 peers:
     Error: Uncaught TypeError: Cannot set property 'needReadable' of undefined (webpack:///~/readable-stream/lib/_stream_transform.js:100:0 <- test/core/bitswap.spec.js:29355)

  

  2) bitswap connections fetches a remote block 3 peers:
     Error: Uncaught TypeError: Cannot set property 'needReadable' of undefined (webpack:///~/readable-stream/lib/_stream_transform.js:100:0 <- test/core/bitswap.spec.js:29355)

  

  3) bitswap connections fetches a remote file 2 peers:
     Error: Uncaught TypeError: Cannot set property 'needReadable' of undefined (webpack:///~/readable-stream/lib/_stream_transform.js:100:0 <- test/core/bitswap.spec.js:29355)
```
### node
```
  1) HTTP API ## custom ipfs-api tests .config .replace updates value:
     Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  2) cli bitswap daemon on (through http-api) wantlist:

      AssertionError: expected '' to deeply equal 'QmUBdnXXPyoDFXj3Hj39dNJ5VkN3QFRskXxcGaYFBB8CNR'
      + expected - actual

      +QmUBdnXXPyoDFXj3Hj39dNJ5VkN3QFRskXxcGaYFBB8CNR
      
      at ipfs.then (test/cli/bitswap.js:21:22)
      at process._tickDomainCallback (internal/process/next_tick.js:129:7)

  3) cli config daemon on (through http-api) replace replace config with file:
     Command failed: /Users/user/projects/ipfs/js-monorepo/packages/js-ipfs/src/cli/bin.js config replace test/test-data/otherconfig
/Users/user/projects/ipfs/js-monorepo/packages/js-ipfs/src/cli/commands/config/replace.js:33
          throw err
          ^

Error: Failed to decode file as config: SyntaxError: Unexpected end of JSON input
    at parseError (/Users/user/projects/ipfs/js-monorepo/packages/js-ipfs/node_modules/ipfs-api/src/request-api.js:16:17)
    at ClientRequest.<anonymous> (/Users/user/projects/ipfs/js-monorepo/packages/js-ipfs/node_modules/ipfs-api/src/request-api.js:37:14)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

  Error: Command failed: /Users/user/projects/ipfs/js-monorepo/packages/js-ipfs/src/cli/bin.js config replace test/test-data/otherconfig
  /Users/user/projects/ipfs/js-monorepo/packages/js-ipfs/src/cli/commands/config/replace.js:33
            throw err
            ^
  
  Error: Failed to decode file as config: SyntaxError: Unexpected end of JSON input
      at parseError (node_modules/ipfs-api/src/request-api.js:16:17)
      at ClientRequest.<anonymous> (node_modules/ipfs-api/src/request-api.js:37:14)
      at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
      at Socket.socketOnData (_http_client.js:363:20)
  
      at Promise.all.then.arr (node_modules/execa/index.js:201:11)
      at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

### browser
```
  1) bitswap connections fetches a remote block 2 peers:
     Error: Uncaught TypeError: Cannot set property 'needReadable' of undefined (webpack:///~/readable-stream/lib/_stream_transform.js:100:0 <- test/core/bitswap.spec.js:29355)

  

  2) bitswap connections fetches a remote block 3 peers:
     Error: Uncaught TypeError: Cannot set property 'needReadable' of undefined (webpack:///~/readable-stream/lib/_stream_transform.js:100:0 <- test/core/bitswap.spec.js:29355)

  

  3) bitswap connections fetches a remote file 2 peers:
     Error: Uncaught TypeError: Cannot set property 'needReadable' of undefined (webpack:///~/readable-stream/lib/_stream_transform.js:100:0 <- test/core/bitswap.spec.js:29355)
```
### node
All passing

Link to full logs: https://ipfs.io/ipfs/QmYyt6qUoDpH3Su3udJ4crq8nXTSr5DkgEgGUyjZ1hqp3k

**Comment by diasdavid** [comment]
fixed on https://github.com/ipfs/js-ipfs/commit/e999f05674dd5e1567cb88b29f60e094b20271fe

Sorry for the troubles, I updated them all by mistake.
