### ISSUE TITLE
Latest yargs update broke jsipfs cli out of jsipfs repo folder

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#806]
`jsipfs daemon` fails if spawned from a folder that is not this repo. There is an assumption on process.cwd()

```
» jsipfs daemon
/Users/koruza/code/js-ipfs/node_modules/yargs/yargs.js:30
  if (!cwd) cwd = process.cwd()
                          ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Yargs (/Users/koruza/code/js-ipfs/node_modules/yargs/yargs.js:30:27)
    at Argv (/Users/koruza/code/js-ipfs/node_modules/yargs/index.js:11:16)
    at Object.<anonymous> (/Users/koruza/code/js-ipfs/node_modules/yargs/index.js:6:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by dignifiedquire** [comment]
@diasdavid is this a problem with the datastore pr as well?

**Comment by diasdavid** [comment]
now it is all good again :)
