### ISSUE TITLE
Fail: cannot find module async/each

### ISSUE THREAD

**Issue by baimurzin** [ipfs/js-ipfs#853]
I have installed ipfs
`npm i ipfs`

Then I call it:
```
const IPFS = require('ipfs');
const ipfs = new IPFS()
```
And got an error:

module.js:471
    throw err;
    ^

Error: Cannot find module 'async/each'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/vladislav/WebstormProjects/testipfs/ipfsdrive/node_modules/libp2p-floodsub/src/index.js:9:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/vladislav/WebstormProjects/testipfs/ipfsdrive/node_modules/ipfs/src/core/components/start.js:5:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

There was no such error before.

UPD.
When i install manually 
`npm i async`

It's work, but as I said before it works without intervention and manually installation.

**Comment by gogogous88** [comment]
same problem when push to heroku:
Error: Cannot find module 'async/each'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/server.js:6:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TuGaiForum@1.0.0 start: `better-npm-run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TuGaiForum@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2017-12-25T21_05_29_337Z-debug.log

**Comment by richardschneider** [comment]
@gogogous88 A lot has happened to IPFS since May.  Please install the latest version `0.27.x`.
