### ISSUE TITLE
"The libp2p node is not started yet" error during discovery

### ISSUE THREAD

**Issue by pgte** [ipfs/js-ipfs#874]
Printed message during the tests:

```
assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: The libp2p node is not started yet
    at Node.dial (/Users/pedroteixeira/projects/ipfs/ipfs-level/node_modules/libp2p/src/index.js:239:5)
    at Node.self._libp2pNode.on (/Users/pedroteixeira/projects/ipfs/ipfs-level/node_modules/ipfs/src/core/components/libp2p.js:29:30)
    at emitOne (events.js:96:13)
    at Node.emit (events.js:188:7)
    at EventEmitter.discovery.on (/Users/pedroteixeira/projects/ipfs/ipfs-level/node_modules/libp2p/src/index.js:71:49)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at WebRTCStar._peerDiscovered (/Users/pedroteixeira/projects/ipfs/ipfs-level/node_modules/libp2p-webrtc-star/src/index.js:241:20)
    at Socket.Emitter.emit (/Users/pedroteixeira/projects/ipfs/ipfs-level/node_modules/libp2p-webrtc-star/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/Users/pedroteixeira/projects/ipfs/ipfs-level/node_modules/libp2p-webrtc-star/node_modules/socket.io-client/lib/socket.js:267:10)
```

Looks like there may be a race condition here, since `self.isOnline()` returns true [here](https://github.com/ipfs/js-ipfs/blob/860165c496f6a00045f76c14b1cd00658bd65edb/src/core/components/libp2p.js#L27), but the libp2p `isOn()` assertion fails [here](https://github.com/libp2p/js-libp2p/blob/2e326e1619c0337d97612c708e94950dfbd9a6ec/src/index.js#L239).

**Comment by pgte** [comment]
I think I found it: https://github.com/ipfs/js-ipfs/blob/860165c496f6a00045f76c14b1cd00658bd65edb/src/core/components/is-online.js#L5

**Comment by pgte** [comment]
Also, and since this is internal, instead asserting the online status, it should queue the operations for when the node is online (like many database clients do).

In this case, the `.dial()` is being called because we discovered a peer. IMO, we should not ignore this event. Instead, we should queue until every networking component (bitswap and libp2p I guess) is considered to be online.

**Comment by pgte** [comment]
Can provide a PR, but would like some guidance before :)

**Comment by diasdavid** [comment]
Interesting, that `if` was added specifically to avoid that race condition. I agree with you, all of these should be queued up. The queueing, however, should not let two dials to be unlocked at the same time, which will confuse libp2p-swarm until it becomes a state machine.

**Comment by pgte** [comment]
ok, I'm onto this..

**Comment by diasdavid** [comment]
@pgte did you get a fix for this?

**Comment by pgte** [comment]
@diasdavid not yet, working around this. Have a local fix, but still lacking some tests.
Will work on a PR for this next week..

**Comment by diasdavid** [comment]
@pgte this is now fixed, right?

**Comment by pgte** [comment]
Yes, should be fixed.

**Comment by diasdavid** [comment]
woot ! thanks @pgte  :)
