### ISSUE TITLE
Attempting to pin from js-ipfs-api results in error

### ISSUE THREAD

**Issue by jmc265** [ipfs/js-ipfs#911]
I am running jsipfs 0.25 in daemon mode. I create and ipfsapi link to the daemon and attempt to pin a file:

```
var ipfs = ipfsAPI({host: 'localhost', port: '5002'});
ipfs.pin.add(hashToPin, (err, ipfsResponse) => {
            if (err) { 
                console.error(err);
                next(err); 
                return; 
            }
            console.log('Pinned hash', hashToPin);
            res.status(200).send({"status": "pinned"});
        });
```
This results in an error:
```
Error: Sorry, something went wrong, please retrace your steps.
[1]     at parseError (/Users/james/Documents/Workspace/IPFS/ppfm/node_modules/ipfs-api/src/request-api.js:17:17)
[1]     at ClientRequest.<anonymous> (/Users/james/Documents/Workspace/IPFS/ppfm/node_modules/ipfs-api/src/request-api.js:39:14)
[1]     at Object.onceWrapper (events.js:290:19)
[1]     at emitOne (events.js:96:13)
[1]     at ClientRequest.emit (events.js:188:7)
[1]     at HTTPParser.parserOnIncomingClient (_http_client.js:473:21)
[1]     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
[1]     at Socket.socketOnData (_http_client.js:362:20)
[1]     at emitOne (events.js:96:13)
[1]     at Socket.emit (events.js:188:7) code: 1
```

Note that when I run the go version of ipfs in daemon mode, this exact same code works. The only variable is the go ipfs daemon --> js ipfs daemon.

**Comment by diasdavid** [comment]
@jmc265 pinning is not yet integrated, WIP PR here https://github.com/ipfs/js-ipfs/pull/107

**Comment by jmc265** [comment]
Sorry!

**Comment by Jacodelange** [comment]
Is there any other way to remove a file?
